//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace ReportBasicLib.WebServiceReport {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceReportSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceReport : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetReportListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportStructOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportSetVarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceReport() {
            //this.Url = global::ReportBasicLib.Properties.Settings.Default.ReportBasicLib_WebServiceReport_ServiceReport;
            //this.Url = AutoLibLocal.ConfigVarTotal.GetServicePath(service_name);
            //this.Url = String.Format("http://{0}/Protocol/ServiceReport.asmx", site);
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetReportListsCompletedEventHandler GetReportListsCompleted;
        
        /// <remarks/>
        public event GetReportStructCompletedEventHandler GetReportStructCompleted;
        
        /// <remarks/>
        public event ReportSetVarCompletedEventHandler ReportSetVarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportLists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetReportLists() {
            object[] results = this.Invoke("GetReportLists", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportListsAsync() {
            this.GetReportListsAsync(null);
        }
        
        /// <remarks/>
        public void GetReportListsAsync(object userState) {
            if ((this.GetReportListsOperationCompleted == null)) {
                this.GetReportListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportListsOperationCompleted);
            }
            this.InvokeAsync("GetReportLists", new object[0], this.GetReportListsOperationCompleted, userState);
        }
        
        private void OnGetReportListsOperationCompleted(object arg) {
            if ((this.GetReportListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportListsCompleted(this, new GetReportListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportStruct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetReportStruct(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            object[] results = this.Invoke("GetReportStruct", new object[] {
                        filename,
                        tHand,
                        tAuto,
                        tMinListFr,
                        tMinListTo,
                        hand_auto});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            this.GetReportStructAsync(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto, null);
        }
        
        /// <remarks/>
        public void GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto, object userState) {
            if ((this.GetReportStructOperationCompleted == null)) {
                this.GetReportStructOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportStructOperationCompleted);
            }
            this.InvokeAsync("GetReportStruct", new object[] {
                        filename,
                        tHand,
                        tAuto,
                        tMinListFr,
                        tMinListTo,
                        hand_auto}, this.GetReportStructOperationCompleted, userState);
        }
        
        private void OnGetReportStructOperationCompleted(object arg) {
            if ((this.GetReportStructCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportStructCompleted(this, new GetReportStructCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportSetVar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReportSetVar(string name, string val) {
            this.Invoke("ReportSetVar", new object[] {
                        name,
                        val});
        }
        
        /// <remarks/>
        public void ReportSetVarAsync(string name, string val) {
            this.ReportSetVarAsync(name, val, null);
        }
        
        /// <remarks/>
        public void ReportSetVarAsync(string name, string val, object userState) {
            if ((this.ReportSetVarOperationCompleted == null)) {
                this.ReportSetVarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportSetVarOperationCompleted);
            }
            this.InvokeAsync("ReportSetVar", new object[] {
                        name,
                        val}, this.ReportSetVarOperationCompleted, userState);
        }
        
        private void OnReportSetVarOperationCompleted(object arg) {
            if ((this.ReportSetVarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportSetVarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetReportListsCompletedEventHandler(object sender, GetReportListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetReportStructCompletedEventHandler(object sender, GetReportStructCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportStructCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportStructCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ReportSetVarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591