//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace SilverlightAutoLibLocal.ServiceReferenceDataSet2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataSet2.WebServiceDataSet2Soap")]
    public interface WebServiceDataSet2Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDataSetFromMdb", ReplyAction="*")]
        System.IAsyncResult BeginGetDataSetFromMdb(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse EndGetDataSetFromMdb(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDataSetFromDsn", ReplyAction="*")]
        System.IAsyncResult BeginGetDataSetFromDsn(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse EndGetDataSetFromDsn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DataSetCommand", ReplyAction="*")]
        System.IAsyncResult BeginDataSetCommand(SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse EndDataSetCommand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetConnectionStringDbType", ReplyAction="*")]
        System.IAsyncResult BeginGetConnectionStringDbType(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse EndGetConnectionStringDbType(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSetFromMdbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSetFromMdb", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequestBody Body;
        
        public GetDataSetFromMdbRequest() {
        }
        
        public GetDataSetFromMdbRequest(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSetFromMdbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string command;
        
        public GetDataSetFromMdbRequestBody() {
        }
        
        public GetDataSetFromMdbRequestBody(string filename, string command) {
            this.filename = filename;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSetFromMdbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSetFromMdbResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponseBody Body;
        
        public GetDataSetFromMdbResponse() {
        }
        
        public GetDataSetFromMdbResponse(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSetFromMdbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataSetFromMdbResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public GetDataSetFromMdbResponseBody() {
        }
        
        public GetDataSetFromMdbResponseBody(string GetDataSetFromMdbResult, string error) {
            this.GetDataSetFromMdbResult = GetDataSetFromMdbResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSetFromDsnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSetFromDsn", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequestBody Body;
        
        public GetDataSetFromDsnRequest() {
        }
        
        public GetDataSetFromDsnRequest(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSetFromDsnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dsn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string command;
        
        public GetDataSetFromDsnRequestBody() {
        }
        
        public GetDataSetFromDsnRequestBody(string dsn, string command) {
            this.dsn = dsn;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSetFromDsnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSetFromDsnResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponseBody Body;
        
        public GetDataSetFromDsnResponse() {
        }
        
        public GetDataSetFromDsnResponse(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSetFromDsnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataSetFromDsnResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public GetDataSetFromDsnResponseBody() {
        }
        
        public GetDataSetFromDsnResponseBody(string GetDataSetFromDsnResult, string error) {
            this.GetDataSetFromDsnResult = GetDataSetFromDsnResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataSetCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataSetCommand", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequestBody Body;
        
        public DataSetCommandRequest() {
        }
        
        public DataSetCommandRequest(SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DataSetCommandRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dsn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string command;
        
        public DataSetCommandRequestBody() {
        }
        
        public DataSetCommandRequestBody(string dsn, string command) {
            this.dsn = dsn;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataSetCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataSetCommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponseBody Body;
        
        public DataSetCommandResponse() {
        }
        
        public DataSetCommandResponse(SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DataSetCommandResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DataSetCommandResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public DataSetCommandResponseBody() {
        }
        
        public DataSetCommandResponseBody(bool DataSetCommandResult, string error) {
            this.DataSetCommandResult = DataSetCommandResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConnectionStringDbTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConnectionStringDbType", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequestBody Body;
        
        public GetConnectionStringDbTypeRequest() {
        }
        
        public GetConnectionStringDbTypeRequest(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConnectionStringDbTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dsn;
        
        public GetConnectionStringDbTypeRequestBody() {
        }
        
        public GetConnectionStringDbTypeRequestBody(string dsn) {
            this.dsn = dsn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConnectionStringDbTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConnectionStringDbTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponseBody Body;
        
        public GetConnectionStringDbTypeResponse() {
        }
        
        public GetConnectionStringDbTypeResponse(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConnectionStringDbTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetConnectionStringDbTypeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int dbtype;
        
        public GetConnectionStringDbTypeResponseBody() {
        }
        
        public GetConnectionStringDbTypeResponseBody(bool GetConnectionStringDbTypeResult, int dbtype) {
            this.GetConnectionStringDbTypeResult = GetConnectionStringDbTypeResult;
            this.dbtype = dbtype;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WebServiceDataSet2SoapChannel : SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetDataSetFromMdbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataSetFromMdbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string error {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetDataSetFromDsnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataSetFromDsnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string error {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataSetCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DataSetCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string error {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetConnectionStringDbTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetConnectionStringDbTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int dbtype {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebServiceDataSet2SoapClient : System.ServiceModel.ClientBase<SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap>, SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap {
        
        private BeginOperationDelegate onBeginGetDataSetFromMdbDelegate;
        
        private EndOperationDelegate onEndGetDataSetFromMdbDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataSetFromMdbCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataSetFromDsnDelegate;
        
        private EndOperationDelegate onEndGetDataSetFromDsnDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataSetFromDsnCompletedDelegate;
        
        private BeginOperationDelegate onBeginDataSetCommandDelegate;
        
        private EndOperationDelegate onEndDataSetCommandDelegate;
        
        private System.Threading.SendOrPostCallback onDataSetCommandCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetConnectionStringDbTypeDelegate;
        
        private EndOperationDelegate onEndGetConnectionStringDbTypeDelegate;
        
        private System.Threading.SendOrPostCallback onGetConnectionStringDbTypeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebServiceDataSet2SoapClient() {
        }
        
        public WebServiceDataSet2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDataSet2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataSet2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataSet2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDataSetFromMdbCompletedEventArgs> GetDataSetFromMdbCompleted;
        
        public event System.EventHandler<GetDataSetFromDsnCompletedEventArgs> GetDataSetFromDsnCompleted;
        
        public event System.EventHandler<DataSetCommandCompletedEventArgs> DataSetCommandCompleted;
        
        public event System.EventHandler<GetConnectionStringDbTypeCompletedEventArgs> GetConnectionStringDbTypeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.BeginGetDataSetFromMdb(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataSetFromMdb(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetDataSetFromMdb(string filename, string command, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequestBody();
            inValue.Body.filename = filename;
            inValue.Body.command = command;
            return ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).BeginGetDataSetFromMdb(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.EndGetDataSetFromMdb(System.IAsyncResult result) {
            return base.Channel.EndGetDataSetFromMdb(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetDataSetFromMdb(System.IAsyncResult result, out string error) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).EndGetDataSetFromMdb(result);
            error = retVal.Body.error;
            return retVal.Body.GetDataSetFromMdbResult;
        }
        
        private System.IAsyncResult OnBeginGetDataSetFromMdb(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string filename = ((string)(inValues[0]));
            string command = ((string)(inValues[1]));
            return this.BeginGetDataSetFromMdb(filename, command, callback, asyncState);
        }
        
        private object[] OnEndGetDataSetFromMdb(System.IAsyncResult result) {
            string error = this.GetDefaultValueForInitialization<string>();
            string retVal = this.EndGetDataSetFromMdb(result, out error);
            return new object[] {
                    error,
                    retVal};
        }
        
        private void OnGetDataSetFromMdbCompleted(object state) {
            if ((this.GetDataSetFromMdbCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataSetFromMdbCompleted(this, new GetDataSetFromMdbCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataSetFromMdbAsync(string filename, string command) {
            this.GetDataSetFromMdbAsync(filename, command, null);
        }
        
        public void GetDataSetFromMdbAsync(string filename, string command, object userState) {
            if ((this.onBeginGetDataSetFromMdbDelegate == null)) {
                this.onBeginGetDataSetFromMdbDelegate = new BeginOperationDelegate(this.OnBeginGetDataSetFromMdb);
            }
            if ((this.onEndGetDataSetFromMdbDelegate == null)) {
                this.onEndGetDataSetFromMdbDelegate = new EndOperationDelegate(this.OnEndGetDataSetFromMdb);
            }
            if ((this.onGetDataSetFromMdbCompletedDelegate == null)) {
                this.onGetDataSetFromMdbCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataSetFromMdbCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataSetFromMdbDelegate, new object[] {
                        filename,
                        command}, this.onEndGetDataSetFromMdbDelegate, this.onGetDataSetFromMdbCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.BeginGetDataSetFromDsn(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataSetFromDsn(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetDataSetFromDsn(string dsn, string command, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequestBody();
            inValue.Body.dsn = dsn;
            inValue.Body.command = command;
            return ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).BeginGetDataSetFromDsn(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.EndGetDataSetFromDsn(System.IAsyncResult result) {
            return base.Channel.EndGetDataSetFromDsn(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetDataSetFromDsn(System.IAsyncResult result, out string error) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).EndGetDataSetFromDsn(result);
            error = retVal.Body.error;
            return retVal.Body.GetDataSetFromDsnResult;
        }
        
        private System.IAsyncResult OnBeginGetDataSetFromDsn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string dsn = ((string)(inValues[0]));
            string command = ((string)(inValues[1]));
            return this.BeginGetDataSetFromDsn(dsn, command, callback, asyncState);
        }
        
        private object[] OnEndGetDataSetFromDsn(System.IAsyncResult result) {
            string error = this.GetDefaultValueForInitialization<string>();
            string retVal = this.EndGetDataSetFromDsn(result, out error);
            return new object[] {
                    error,
                    retVal};
        }
        
        private void OnGetDataSetFromDsnCompleted(object state) {
            if ((this.GetDataSetFromDsnCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataSetFromDsnCompleted(this, new GetDataSetFromDsnCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataSetFromDsnAsync(string dsn, string command) {
            this.GetDataSetFromDsnAsync(dsn, command, null);
        }
        
        public void GetDataSetFromDsnAsync(string dsn, string command, object userState) {
            if ((this.onBeginGetDataSetFromDsnDelegate == null)) {
                this.onBeginGetDataSetFromDsnDelegate = new BeginOperationDelegate(this.OnBeginGetDataSetFromDsn);
            }
            if ((this.onEndGetDataSetFromDsnDelegate == null)) {
                this.onEndGetDataSetFromDsnDelegate = new EndOperationDelegate(this.OnEndGetDataSetFromDsn);
            }
            if ((this.onGetDataSetFromDsnCompletedDelegate == null)) {
                this.onGetDataSetFromDsnCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataSetFromDsnCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataSetFromDsnDelegate, new object[] {
                        dsn,
                        command}, this.onEndGetDataSetFromDsnDelegate, this.onGetDataSetFromDsnCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.BeginDataSetCommand(SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDataSetCommand(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDataSetCommand(string dsn, string command, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequestBody();
            inValue.Body.dsn = dsn;
            inValue.Body.command = command;
            return ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).BeginDataSetCommand(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.EndDataSetCommand(System.IAsyncResult result) {
            return base.Channel.EndDataSetCommand(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndDataSetCommand(System.IAsyncResult result, out string error) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).EndDataSetCommand(result);
            error = retVal.Body.error;
            return retVal.Body.DataSetCommandResult;
        }
        
        private System.IAsyncResult OnBeginDataSetCommand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string dsn = ((string)(inValues[0]));
            string command = ((string)(inValues[1]));
            return this.BeginDataSetCommand(dsn, command, callback, asyncState);
        }
        
        private object[] OnEndDataSetCommand(System.IAsyncResult result) {
            string error = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndDataSetCommand(result, out error);
            return new object[] {
                    error,
                    retVal};
        }
        
        private void OnDataSetCommandCompleted(object state) {
            if ((this.DataSetCommandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DataSetCommandCompleted(this, new DataSetCommandCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DataSetCommandAsync(string dsn, string command) {
            this.DataSetCommandAsync(dsn, command, null);
        }
        
        public void DataSetCommandAsync(string dsn, string command, object userState) {
            if ((this.onBeginDataSetCommandDelegate == null)) {
                this.onBeginDataSetCommandDelegate = new BeginOperationDelegate(this.OnBeginDataSetCommand);
            }
            if ((this.onEndDataSetCommandDelegate == null)) {
                this.onEndDataSetCommandDelegate = new EndOperationDelegate(this.OnEndDataSetCommand);
            }
            if ((this.onDataSetCommandCompletedDelegate == null)) {
                this.onDataSetCommandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDataSetCommandCompleted);
            }
            base.InvokeAsync(this.onBeginDataSetCommandDelegate, new object[] {
                        dsn,
                        command}, this.onEndDataSetCommandDelegate, this.onDataSetCommandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.BeginGetConnectionStringDbType(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetConnectionStringDbType(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetConnectionStringDbType(string dsn, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequestBody();
            inValue.Body.dsn = dsn;
            return ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).BeginGetConnectionStringDbType(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap.EndGetConnectionStringDbType(System.IAsyncResult result) {
            return base.Channel.EndGetConnectionStringDbType(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndGetConnectionStringDbType(System.IAsyncResult result, out int dbtype) {
            SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap)(this)).EndGetConnectionStringDbType(result);
            dbtype = retVal.Body.dbtype;
            return retVal.Body.GetConnectionStringDbTypeResult;
        }
        
        private System.IAsyncResult OnBeginGetConnectionStringDbType(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string dsn = ((string)(inValues[0]));
            return this.BeginGetConnectionStringDbType(dsn, callback, asyncState);
        }
        
        private object[] OnEndGetConnectionStringDbType(System.IAsyncResult result) {
            int dbtype = this.GetDefaultValueForInitialization<int>();
            bool retVal = this.EndGetConnectionStringDbType(result, out dbtype);
            return new object[] {
                    dbtype,
                    retVal};
        }
        
        private void OnGetConnectionStringDbTypeCompleted(object state) {
            if ((this.GetConnectionStringDbTypeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetConnectionStringDbTypeCompleted(this, new GetConnectionStringDbTypeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetConnectionStringDbTypeAsync(string dsn) {
            this.GetConnectionStringDbTypeAsync(dsn, null);
        }
        
        public void GetConnectionStringDbTypeAsync(string dsn, object userState) {
            if ((this.onBeginGetConnectionStringDbTypeDelegate == null)) {
                this.onBeginGetConnectionStringDbTypeDelegate = new BeginOperationDelegate(this.OnBeginGetConnectionStringDbType);
            }
            if ((this.onEndGetConnectionStringDbTypeDelegate == null)) {
                this.onEndGetConnectionStringDbTypeDelegate = new EndOperationDelegate(this.OnEndGetConnectionStringDbType);
            }
            if ((this.onGetConnectionStringDbTypeCompletedDelegate == null)) {
                this.onGetConnectionStringDbTypeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetConnectionStringDbTypeCompleted);
            }
            base.InvokeAsync(this.onBeginGetConnectionStringDbTypeDelegate, new object[] {
                        dsn}, this.onEndGetConnectionStringDbTypeDelegate, this.onGetConnectionStringDbTypeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap CreateChannel() {
            return new WebServiceDataSet2SoapClientChannel(this);
        }
        
        private class WebServiceDataSet2SoapClientChannel : ChannelBase<SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap>, SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap {
            
            public WebServiceDataSet2SoapClientChannel(System.ServiceModel.ClientBase<SilverlightAutoLibLocal.ServiceReferenceDataSet2.WebServiceDataSet2Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetDataSetFromMdb(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetDataSetFromMdb", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse EndGetDataSetFromMdb(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromMdbResponse)(base.EndInvoke("GetDataSetFromMdb", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDataSetFromDsn(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetDataSetFromDsn", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse EndGetDataSetFromDsn(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetDataSetFromDsnResponse)(base.EndInvoke("GetDataSetFromDsn", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDataSetCommand(SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DataSetCommand", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse EndDataSetCommand(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.DataSetCommandResponse)(base.EndInvoke("DataSetCommand", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetConnectionStringDbType(SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetConnectionStringDbType", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse EndGetConnectionStringDbType(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceDataSet2.GetConnectionStringDbTypeResponse)(base.EndInvoke("GetConnectionStringDbType", _args, result)));
                return _result;
            }
        }
    }
}
