//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceDataGateServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy")]
    public interface IWcfServiceDataGateServerProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/CheckServerEvent", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/CheckServerEventResponse")]
        string CheckServerEvent(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/CheckServerEvent", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/CheckServerEventResponse")]
        System.Threading.Tasks.Task<string> CheckServerEventAsync(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/GetAlarmEvents", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/GetAlarmEventsResponse")]
        string GetAlarmEvents(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/GetAlarmEvents", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/GetAlarmEventsResponse")]
        System.Threading.Tasks.Task<string> GetAlarmEventsAsync(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/ExecuteCommand", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/ExecuteCommandResponse")]
        bool ExecuteCommand(int id, string command, string argument, string hash, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/ExecuteCommand", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<bool> ExecuteCommandAsync(int id, string command, string argument, string hash, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/CommonMethod", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/CommonMethodResponse")]
        AutoLib.ServiceReferenceDataGateServer.CommonMethodResponse CommonMethod(AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDataGateServerProxy/CommonMethod", ReplyAction="http://tempuri.org/IWcfServiceDataGateServerProxy/CommonMethodResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataGateServer.CommonMethodResponse> CommonMethodAsync(AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommonMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommonMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[][] args;
        
        public CommonMethodRequest() {
        }
        
        public CommonMethodRequest(byte[][] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommonMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommonMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CommonMethodResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[][] result;
        
        public CommonMethodResponse() {
        }
        
        public CommonMethodResponse(int CommonMethodResult, byte[][] result) {
            this.CommonMethodResult = CommonMethodResult;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceDataGateServerProxyChannel : AutoLib.ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceDataGateServerProxyClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy>, AutoLib.ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy {
        
        public WcfServiceDataGateServerProxyClient() {
        }
        
        public WcfServiceDataGateServerProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceDataGateServerProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDataGateServerProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDataGateServerProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckServerEvent(int id, string hash) {
            return base.Channel.CheckServerEvent(id, hash);
        }
        
        public System.Threading.Tasks.Task<string> CheckServerEventAsync(int id, string hash) {
            return base.Channel.CheckServerEventAsync(id, hash);
        }
        
        public string GetAlarmEvents(int id, string hash) {
            return base.Channel.GetAlarmEvents(id, hash);
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmEventsAsync(int id, string hash) {
            return base.Channel.GetAlarmEventsAsync(id, hash);
        }
        
        public bool ExecuteCommand(int id, string command, string argument, string hash, string guid) {
            return base.Channel.ExecuteCommand(id, command, argument, hash, guid);
        }
        
        public System.Threading.Tasks.Task<bool> ExecuteCommandAsync(int id, string command, string argument, string hash, string guid) {
            return base.Channel.ExecuteCommandAsync(id, command, argument, hash, guid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceDataGateServer.CommonMethodResponse AutoLib.ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy.CommonMethod(AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest request) {
            return base.Channel.CommonMethod(request);
        }
        
        public int CommonMethod(byte[][] args, out byte[][] result) {
            AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest inValue = new AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest();
            inValue.args = args;
            AutoLib.ServiceReferenceDataGateServer.CommonMethodResponse retVal = ((AutoLib.ServiceReferenceDataGateServer.IWcfServiceDataGateServerProxy)(this)).CommonMethod(inValue);
            result = retVal.result;
            return retVal.CommonMethodResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataGateServer.CommonMethodResponse> CommonMethodAsync(AutoLib.ServiceReferenceDataGateServer.CommonMethodRequest request) {
            return base.Channel.CommonMethodAsync(request);
        }
    }
}
