//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceOdbc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceOdbc.IServiceOdbc")]
    public interface IServiceOdbc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOdbc/GetDataSetFromOdbc", ReplyAction="http://tempuri.org/IServiceOdbc/GetDataSetFromOdbcResponse")]
        AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcResponse GetDataSetFromOdbc(AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOdbc/GetDataSetFromOdbc", ReplyAction="http://tempuri.org/IServiceOdbc/GetDataSetFromOdbcResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcResponse> GetDataSetFromOdbcAsync(AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOdbc/DataSetOdbcCommand", ReplyAction="http://tempuri.org/IServiceOdbc/DataSetOdbcCommandResponse")]
        AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandResponse DataSetOdbcCommand(AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOdbc/DataSetOdbcCommand", ReplyAction="http://tempuri.org/IServiceOdbc/DataSetOdbcCommandResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandResponse> DataSetOdbcCommandAsync(AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromOdbc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromOdbcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string command;
        
        public GetDataSetFromOdbcRequest() {
        }
        
        public GetDataSetFromOdbcRequest(string dsn, string command) {
            this.dsn = dsn;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromOdbcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromOdbcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetDataSetFromOdbcResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public GetDataSetFromOdbcResponse() {
        }
        
        public GetDataSetFromOdbcResponse(System.Data.DataSet GetDataSetFromOdbcResult, string error) {
            this.GetDataSetFromOdbcResult = GetDataSetFromOdbcResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetOdbcCommand", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetOdbcCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string command;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string guid;
        
        public DataSetOdbcCommandRequest() {
        }
        
        public DataSetOdbcCommandRequest(string dsn, string command, string guid) {
            this.dsn = dsn;
            this.command = command;
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetOdbcCommandResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetOdbcCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DataSetOdbcCommandResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public DataSetOdbcCommandResponse() {
        }
        
        public DataSetOdbcCommandResponse(bool DataSetOdbcCommandResult, string error) {
            this.DataSetOdbcCommandResult = DataSetOdbcCommandResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOdbcChannel : AutoLib.ServiceReferenceOdbc.IServiceOdbc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOdbcClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceOdbc.IServiceOdbc>, AutoLib.ServiceReferenceOdbc.IServiceOdbc {
        
        public ServiceOdbcClient() {
        }
        
        public ServiceOdbcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOdbcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOdbcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOdbcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcResponse AutoLib.ServiceReferenceOdbc.IServiceOdbc.GetDataSetFromOdbc(AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest request) {
            return base.Channel.GetDataSetFromOdbc(request);
        }
        
        public System.Data.DataSet GetDataSetFromOdbc(string dsn, string command, out string error) {
            AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest inValue = new AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest();
            inValue.dsn = dsn;
            inValue.command = command;
            AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcResponse retVal = ((AutoLib.ServiceReferenceOdbc.IServiceOdbc)(this)).GetDataSetFromOdbc(inValue);
            error = retVal.error;
            return retVal.GetDataSetFromOdbcResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcResponse> GetDataSetFromOdbcAsync(AutoLib.ServiceReferenceOdbc.GetDataSetFromOdbcRequest request) {
            return base.Channel.GetDataSetFromOdbcAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandResponse AutoLib.ServiceReferenceOdbc.IServiceOdbc.DataSetOdbcCommand(AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest request) {
            return base.Channel.DataSetOdbcCommand(request);
        }
        
        public bool DataSetOdbcCommand(string dsn, string command, string guid, out string error) {
            AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest inValue = new AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest();
            inValue.dsn = dsn;
            inValue.command = command;
            inValue.guid = guid;
            AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandResponse retVal = ((AutoLib.ServiceReferenceOdbc.IServiceOdbc)(this)).DataSetOdbcCommand(inValue);
            error = retVal.error;
            return retVal.DataSetOdbcCommandResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandResponse> DataSetOdbcCommandAsync(AutoLib.ServiceReferenceOdbc.DataSetOdbcCommandRequest request) {
            return base.Channel.DataSetOdbcCommandAsync(request);
        }
    }
}
