//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTools.ServiceReferenceUsername {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsername.ServiceUsername2Soap")]
    public interface ServiceUsername2Soap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 siteid_hash이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        WebTools.ServiceReferenceUsername.LogInResponse LogIn(WebTools.ServiceReferenceUsername.LogInRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 siteid_hash이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformation", ReplyAction="*")]
        WebTools.ServiceReferenceUsername.GetUserInformationResponse GetUserInformation(WebTools.ServiceReferenceUsername.GetUserInformationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceUsername.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(WebTools.ServiceReferenceUsername.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string siteid_hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usernamehash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] passcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ui_culture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string seed;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string siteid_hash, string usernamehash, byte[] passcode, string ui_culture, byte[] hash, string seed) {
            this.siteid_hash = siteid_hash;
            this.usernamehash = usernamehash;
            this.passcode = passcode;
            this.ui_culture = ui_culture;
            this.hash = hash;
            this.seed = seed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceUsername.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(WebTools.ServiceReferenceUsername.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult, string err_msg) {
            this.LogInResult = LogInResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformation", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceUsername.GetUserInformationRequestBody Body;
        
        public GetUserInformationRequest() {
        }
        
        public GetUserInformationRequest(WebTools.ServiceReferenceUsername.GetUserInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string siteid_hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username_hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string infoitem_hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string seed;
        
        public GetUserInformationRequestBody() {
        }
        
        public GetUserInformationRequestBody(string siteid_hash, string username_hash, string infoitem_hash, byte[] hash, string seed) {
            this.siteid_hash = siteid_hash;
            this.username_hash = username_hash;
            this.infoitem_hash = infoitem_hash;
            this.hash = hash;
            this.seed = seed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceUsername.GetUserInformationResponseBody Body;
        
        public GetUserInformationResponse() {
        }
        
        public GetUserInformationResponse(WebTools.ServiceReferenceUsername.GetUserInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetUserInformationResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string err_msg;
        
        public GetUserInformationResponseBody() {
        }
        
        public GetUserInformationResponseBody(bool GetUserInformationResult, string item_value, string err_msg) {
            this.GetUserInformationResult = GetUserInformationResult;
            this.item_value = item_value;
            this.err_msg = err_msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceUsername2SoapChannel : WebTools.ServiceReferenceUsername.ServiceUsername2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsername2SoapClient : System.ServiceModel.ClientBase<WebTools.ServiceReferenceUsername.ServiceUsername2Soap>, WebTools.ServiceReferenceUsername.ServiceUsername2Soap {
        
        public ServiceUsername2SoapClient() {
        }
        
        public ServiceUsername2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsername2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsername2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsername2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTools.ServiceReferenceUsername.LogInResponse WebTools.ServiceReferenceUsername.ServiceUsername2Soap.LogIn(WebTools.ServiceReferenceUsername.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string siteid_hash, string usernamehash, byte[] passcode, string ui_culture, byte[] hash, string seed, out string err_msg) {
            WebTools.ServiceReferenceUsername.LogInRequest inValue = new WebTools.ServiceReferenceUsername.LogInRequest();
            inValue.Body = new WebTools.ServiceReferenceUsername.LogInRequestBody();
            inValue.Body.siteid_hash = siteid_hash;
            inValue.Body.usernamehash = usernamehash;
            inValue.Body.passcode = passcode;
            inValue.Body.ui_culture = ui_culture;
            inValue.Body.hash = hash;
            inValue.Body.seed = seed;
            WebTools.ServiceReferenceUsername.LogInResponse retVal = ((WebTools.ServiceReferenceUsername.ServiceUsername2Soap)(this)).LogIn(inValue);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTools.ServiceReferenceUsername.GetUserInformationResponse WebTools.ServiceReferenceUsername.ServiceUsername2Soap.GetUserInformation(WebTools.ServiceReferenceUsername.GetUserInformationRequest request) {
            return base.Channel.GetUserInformation(request);
        }
        
        public bool GetUserInformation(string siteid_hash, string username_hash, string infoitem_hash, byte[] hash, string seed, out string item_value, out string err_msg) {
            WebTools.ServiceReferenceUsername.GetUserInformationRequest inValue = new WebTools.ServiceReferenceUsername.GetUserInformationRequest();
            inValue.Body = new WebTools.ServiceReferenceUsername.GetUserInformationRequestBody();
            inValue.Body.siteid_hash = siteid_hash;
            inValue.Body.username_hash = username_hash;
            inValue.Body.infoitem_hash = infoitem_hash;
            inValue.Body.hash = hash;
            inValue.Body.seed = seed;
            WebTools.ServiceReferenceUsername.GetUserInformationResponse retVal = ((WebTools.ServiceReferenceUsername.ServiceUsername2Soap)(this)).GetUserInformation(inValue);
            item_value = retVal.Body.item_value;
            err_msg = retVal.Body.err_msg;
            return retVal.Body.GetUserInformationResult;
        }
    }
}
