//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceDataTag {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataTag.IServiceDataTag")]
    public interface IServiceDataTag {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/CheckServiceAlive", ReplyAction="http://tempuri.org/IServiceDataTag/CheckServiceAliveResponse")]
        int CheckServiceAlive(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/CheckServiceAlive", ReplyAction="http://tempuri.org/IServiceDataTag/CheckServiceAliveResponse")]
        System.Threading.Tasks.Task<int> CheckServiceAliveAsync(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetTagValueList", ReplyAction="http://tempuri.org/IServiceDataTag/GetTagValueListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet GetTagValueList(object[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetTagValueList", ReplyAction="http://tempuri.org/IServiceDataTag/GetTagValueListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTagValueListAsync(object[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/WriteCurrAI", ReplyAction="http://tempuri.org/IServiceDataTag/WriteCurrAIResponse")]
        bool WriteCurrAI(string tag, double val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/WriteCurrAI", ReplyAction="http://tempuri.org/IServiceDataTag/WriteCurrAIResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrAIAsync(string tag, double val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/WriteCurrST", ReplyAction="http://tempuri.org/IServiceDataTag/WriteCurrSTResponse")]
        bool WriteCurrST(string tag, string val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/WriteCurrST", ReplyAction="http://tempuri.org/IServiceDataTag/WriteCurrSTResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrSTAsync(string tag, string val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetDataAi", ReplyAction="http://tempuri.org/IServiceDataTag/GetDataAiResponse")]
        System.Data.DataSet GetDataAi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetDataAi", ReplyAction="http://tempuri.org/IServiceDataTag/GetDataAiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetDataDi", ReplyAction="http://tempuri.org/IServiceDataTag/GetDataDiResponse")]
        System.Data.DataSet GetDataDi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetDataDi", ReplyAction="http://tempuri.org/IServiceDataTag/GetDataDiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataDiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetLogLists", ReplyAction="http://tempuri.org/IServiceDataTag/GetLogListsResponse")]
        System.Data.DataSet GetLogLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetLogLists", ReplyAction="http://tempuri.org/IServiceDataTag/GetLogListsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLogListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetLogFile", ReplyAction="http://tempuri.org/IServiceDataTag/GetLogFileResponse")]
        System.Data.DataSet GetLogFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetLogFile", ReplyAction="http://tempuri.org/IServiceDataTag/GetLogFileResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLogFileAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmLists", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmListsResponse")]
        System.Data.DataSet GetAlarmLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmLists", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmListsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFile", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileResponse")]
        System.Data.DataSet GetAlarmFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFile", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileByScriptResponse")]
        System.Data.DataSet GetAlarmFileByScript(int year, int month, int day, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileByScriptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileByScriptAsync(int year, int month, int day, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript2", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript2Response")]
        System.Data.DataSet GetAlarmFileByScript2(System.DateTime tFrom, System.DateTime tTo, string option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript2", ReplyAction="http://tempuri.org/IServiceDataTag/GetAlarmFileByScript2Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileByScript2Async(System.DateTime tFrom, System.DateTime tTo, string option);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataTagChannel : AutoLib.ServiceReferenceDataTag.IServiceDataTag, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataTagClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceDataTag.IServiceDataTag>, AutoLib.ServiceReferenceDataTag.IServiceDataTag {
        
        public ServiceDataTagClient() {
        }
        
        public ServiceDataTagClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataTagClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataTagClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataTagClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckServiceAlive(int val) {
            return base.Channel.CheckServiceAlive(val);
        }
        
        public System.Threading.Tasks.Task<int> CheckServiceAliveAsync(int val) {
            return base.Channel.CheckServiceAliveAsync(val);
        }
        
        public System.Data.DataSet GetTagValueList(object[] array) {
            return base.Channel.GetTagValueList(array);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTagValueListAsync(object[] array) {
            return base.Channel.GetTagValueListAsync(array);
        }
        
        public bool WriteCurrAI(string tag, double val, string guid) {
            return base.Channel.WriteCurrAI(tag, val, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrAIAsync(string tag, double val, string guid) {
            return base.Channel.WriteCurrAIAsync(tag, val, guid);
        }
        
        public bool WriteCurrST(string tag, string val, string guid) {
            return base.Channel.WriteCurrST(tag, val, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrSTAsync(string tag, string val, string guid) {
            return base.Channel.WriteCurrSTAsync(tag, val, guid);
        }
        
        public System.Data.DataSet GetDataAi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataAi(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataAiAsync(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Data.DataSet GetDataDi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataDi(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataDiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataDiAsync(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Data.DataSet GetLogLists() {
            return base.Channel.GetLogLists();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLogListsAsync() {
            return base.Channel.GetLogListsAsync();
        }
        
        public System.Data.DataSet GetLogFile(string name) {
            return base.Channel.GetLogFile(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLogFileAsync(string name) {
            return base.Channel.GetLogFileAsync(name);
        }
        
        public System.Data.DataSet GetAlarmLists() {
            return base.Channel.GetAlarmLists();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmListsAsync() {
            return base.Channel.GetAlarmListsAsync();
        }
        
        public System.Data.DataSet GetAlarmFile(string name) {
            return base.Channel.GetAlarmFile(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileAsync(string name) {
            return base.Channel.GetAlarmFileAsync(name);
        }
        
        public System.Data.DataSet GetAlarmFileByScript(int year, int month, int day, int option) {
            return base.Channel.GetAlarmFileByScript(year, month, day, option);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileByScriptAsync(int year, int month, int day, int option) {
            return base.Channel.GetAlarmFileByScriptAsync(year, month, day, option);
        }
        
        public System.Data.DataSet GetAlarmFileByScript2(System.DateTime tFrom, System.DateTime tTo, string option) {
            return base.Channel.GetAlarmFileByScript2(tFrom, tTo, option);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAlarmFileByScript2Async(System.DateTime tFrom, System.DateTime tTo, string option) {
            return base.Channel.GetAlarmFileByScript2Async(tFrom, tTo, option);
        }
    }
}
