//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceDataTag2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataTag2.IWebServiceDataTag2")]
    public interface IWebServiceDataTag2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/CheckServiceAlive", ReplyAction="http://tempuri.org/IWebServiceDataTag2/CheckServiceAliveResponse")]
        int CheckServiceAlive(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/CheckServiceAlive", ReplyAction="http://tempuri.org/IWebServiceDataTag2/CheckServiceAliveResponse")]
        System.Threading.Tasks.Task<int> CheckServiceAliveAsync(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetTagValueLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetTagValueListsResponse")]
        string GetTagValueLists(string[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetTagValueLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetTagValueListsResponse")]
        System.Threading.Tasks.Task<string> GetTagValueListsAsync(string[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurrAI", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrAIResponse")]
        bool WriteCurrAI(string tag, double val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurrAI", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrAIResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrAIAsync(string tag, double val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurrST", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrSTResponse")]
        bool WriteCurrST(string tag, string val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurrST", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrSTResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrSTAsync(string tag, string val, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetDataAi", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetDataAiResponse")]
        string GetDataAi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetDataAi", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetDataAiResponse")]
        System.Threading.Tasks.Task<string> GetDataAiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetDataDi", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetDataDiResponse")]
        string GetDataDi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetDataDi", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetDataDiResponse")]
        System.Threading.Tasks.Task<string> GetDataDiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetLogLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetLogListsResponse")]
        string GetLogLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetLogLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetLogListsResponse")]
        System.Threading.Tasks.Task<string> GetLogListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetLogFile", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetLogFileResponse")]
        string GetLogFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetLogFile", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetLogFileResponse")]
        System.Threading.Tasks.Task<string> GetLogFileAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmListsResponse")]
        string GetAlarmLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmLists", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmListsResponse")]
        System.Threading.Tasks.Task<string> GetAlarmListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmFile", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileResponse")]
        string GetAlarmFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmFile", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileResponse")]
        System.Threading.Tasks.Task<string> GetAlarmFileAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileByScript2", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileByScript2Response")]
        string GetAlarmFileByScript2(System.DateTime tFrom, System.DateTime tTo, string option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileByScript2", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetAlarmFileByScript2Response")]
        System.Threading.Tasks.Task<string> GetAlarmFileByScript2Async(System.DateTime tFrom, System.DateTime tTo, string option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetServerVersion", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetServerVersionResponse")]
        string GetServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetServerVersion", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetServerVersionResponse")]
        System.Threading.Tasks.Task<string> GetServerVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetServerInformations", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetServerInformationsResponse")]
        string GetServerInformations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/GetServerInformations", ReplyAction="http://tempuri.org/IWebServiceDataTag2/GetServerInformationsResponse")]
        System.Threading.Tasks.Task<string> GetServerInformationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurr", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrResponse")]
        bool WriteCurr(string username, string computername, string tag, string val, byte[] hash, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceDataTag2/WriteCurr", ReplyAction="http://tempuri.org/IWebServiceDataTag2/WriteCurrResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrAsync(string username, string computername, string tag, string val, byte[] hash, string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceDataTag2Channel : AutoLib.ServiceReferenceDataTag2.IWebServiceDataTag2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDataTag2Client : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceDataTag2.IWebServiceDataTag2>, AutoLib.ServiceReferenceDataTag2.IWebServiceDataTag2 {
        
        public WebServiceDataTag2Client() {
        }
        
        public WebServiceDataTag2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDataTag2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataTag2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDataTag2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckServiceAlive(int val) {
            return base.Channel.CheckServiceAlive(val);
        }
        
        public System.Threading.Tasks.Task<int> CheckServiceAliveAsync(int val) {
            return base.Channel.CheckServiceAliveAsync(val);
        }
        
        public string GetTagValueLists(string[] array) {
            return base.Channel.GetTagValueLists(array);
        }
        
        public System.Threading.Tasks.Task<string> GetTagValueListsAsync(string[] array) {
            return base.Channel.GetTagValueListsAsync(array);
        }
        
        public bool WriteCurrAI(string tag, double val, string guid) {
            return base.Channel.WriteCurrAI(tag, val, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrAIAsync(string tag, double val, string guid) {
            return base.Channel.WriteCurrAIAsync(tag, val, guid);
        }
        
        public bool WriteCurrST(string tag, string val, string guid) {
            return base.Channel.WriteCurrST(tag, val, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrSTAsync(string tag, string val, string guid) {
            return base.Channel.WriteCurrSTAsync(tag, val, guid);
        }
        
        public string GetDataAi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataAi(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataAiAsync(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public string GetDataDi(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataDi(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public System.Threading.Tasks.Task<string> GetDataDiAsync(string tag, int value_type, int data_time, int year, int mon, int day, int hour, int min, int data_count, int data_gab) {
            return base.Channel.GetDataDiAsync(tag, value_type, data_time, year, mon, day, hour, min, data_count, data_gab);
        }
        
        public string GetLogLists() {
            return base.Channel.GetLogLists();
        }
        
        public System.Threading.Tasks.Task<string> GetLogListsAsync() {
            return base.Channel.GetLogListsAsync();
        }
        
        public string GetLogFile(string name) {
            return base.Channel.GetLogFile(name);
        }
        
        public System.Threading.Tasks.Task<string> GetLogFileAsync(string name) {
            return base.Channel.GetLogFileAsync(name);
        }
        
        public string GetAlarmLists() {
            return base.Channel.GetAlarmLists();
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmListsAsync() {
            return base.Channel.GetAlarmListsAsync();
        }
        
        public string GetAlarmFile(string name) {
            return base.Channel.GetAlarmFile(name);
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmFileAsync(string name) {
            return base.Channel.GetAlarmFileAsync(name);
        }
        
        public string GetAlarmFileByScript2(System.DateTime tFrom, System.DateTime tTo, string option) {
            return base.Channel.GetAlarmFileByScript2(tFrom, tTo, option);
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmFileByScript2Async(System.DateTime tFrom, System.DateTime tTo, string option) {
            return base.Channel.GetAlarmFileByScript2Async(tFrom, tTo, option);
        }
        
        public string GetServerVersion() {
            return base.Channel.GetServerVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetServerVersionAsync() {
            return base.Channel.GetServerVersionAsync();
        }
        
        public string GetServerInformations() {
            return base.Channel.GetServerInformations();
        }
        
        public System.Threading.Tasks.Task<string> GetServerInformationsAsync() {
            return base.Channel.GetServerInformationsAsync();
        }
        
        public bool WriteCurr(string username, string computername, string tag, string val, byte[] hash, string guid) {
            return base.Channel.WriteCurr(username, computername, tag, val, hash, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrAsync(string username, string computername, string tag, string val, byte[] hash, string guid) {
            return base.Channel.WriteCurrAsync(username, computername, tag, val, hash, guid);
        }
    }
}
