//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceService3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceService3.IWebService3")]
    public interface IWebService3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetConversationKey", ReplyAction="http://tempuri.org/IWebService3/GetConversationKeyResponse")]
        AutoLib.ServiceReferenceService3.GetConversationKeyResponse GetConversationKey(AutoLib.ServiceReferenceService3.GetConversationKeyRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetConversationKey", ReplyAction="http://tempuri.org/IWebService3/GetConversationKeyResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetConversationKeyResponse> GetConversationKeyAsync(AutoLib.ServiceReferenceService3.GetConversationKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/DefaultUserCheck", ReplyAction="http://tempuri.org/IWebService3/DefaultUserCheckResponse")]
        AutoLib.ServiceReferenceService3.DefaultUserCheckResponse DefaultUserCheck(AutoLib.ServiceReferenceService3.DefaultUserCheckRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/DefaultUserCheck", ReplyAction="http://tempuri.org/IWebService3/DefaultUserCheckResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.DefaultUserCheckResponse> DefaultUserCheckAsync(AutoLib.ServiceReferenceService3.DefaultUserCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/CheckUserName", ReplyAction="http://tempuri.org/IWebService3/CheckUserNameResponse")]
        AutoLib.ServiceReferenceService3.CheckUserNameResponse CheckUserName(AutoLib.ServiceReferenceService3.CheckUserNameRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/CheckUserName", ReplyAction="http://tempuri.org/IWebService3/CheckUserNameResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.CheckUserNameResponse> CheckUserNameAsync(AutoLib.ServiceReferenceService3.CheckUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/WriteCurr", ReplyAction="http://tempuri.org/IWebService3/WriteCurrResponse")]
        bool WriteCurr(string key_enc, string username_enc, string computername_enc, string tag_enc, string val_enc, byte[] hash, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/WriteCurr", ReplyAction="http://tempuri.org/IWebService3/WriteCurrResponse")]
        System.Threading.Tasks.Task<bool> WriteCurrAsync(string key_enc, string username_enc, string computername_enc, string tag_enc, string val_enc, byte[] hash, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetDataSetFromMdb", ReplyAction="http://tempuri.org/IWebService3/GetDataSetFromMdbResponse")]
        AutoLib.ServiceReferenceService3.GetDataSetFromMdbResponse GetDataSetFromMdb(AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetDataSetFromMdb", ReplyAction="http://tempuri.org/IWebService3/GetDataSetFromMdbResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetDataSetFromMdbResponse> GetDataSetFromMdbAsync(AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetDataSetFromDsn", ReplyAction="http://tempuri.org/IWebService3/GetDataSetFromDsnResponse")]
        AutoLib.ServiceReferenceService3.GetDataSetFromDsnResponse GetDataSetFromDsn(AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetDataSetFromDsn", ReplyAction="http://tempuri.org/IWebService3/GetDataSetFromDsnResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetDataSetFromDsnResponse> GetDataSetFromDsnAsync(AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/DataSetCommand", ReplyAction="http://tempuri.org/IWebService3/DataSetCommandResponse")]
        AutoLib.ServiceReferenceService3.DataSetCommandResponse DataSetCommand(AutoLib.ServiceReferenceService3.DataSetCommandRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/DataSetCommand", ReplyAction="http://tempuri.org/IWebService3/DataSetCommandResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.DataSetCommandResponse> DataSetCommandAsync(AutoLib.ServiceReferenceService3.DataSetCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetConnectionStringDbType", ReplyAction="http://tempuri.org/IWebService3/GetConnectionStringDbTypeResponse")]
        AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeResponse GetConnectionStringDbType(AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService3/GetConnectionStringDbType", ReplyAction="http://tempuri.org/IWebService3/GetConnectionStringDbTypeResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeResponse> GetConnectionStringDbTypeAsync(AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConversationKey", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConversationKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string request;
        
        public GetConversationKeyRequest() {
        }
        
        public GetConversationKeyRequest(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConversationKeyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConversationKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetConversationKeyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string key2_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string key3_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string key4_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string key5_enc;
        
        public GetConversationKeyResponse() {
        }
        
        public GetConversationKeyResponse(string GetConversationKeyResult, string key2_enc, string key3_enc, string key4_enc, string key5_enc) {
            this.GetConversationKeyResult = GetConversationKeyResult;
            this.key2_enc = key2_enc;
            this.key3_enc = key3_enc;
            this.key4_enc = key4_enc;
            this.key5_enc = key5_enc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheck", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clientGuid;
        
        public DefaultUserCheckRequest() {
        }
        
        public DefaultUserCheckRequest(string key_enc, byte[] hash, string clientGuid) {
            this.key_enc = key_enc;
            this.hash = hash;
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheckResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DefaultUserCheckResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool bTrialMode;
        
        public DefaultUserCheckResponse() {
        }
        
        public DefaultUserCheckResponse(bool DefaultUserCheckResult, string username_enc, string err_msg, bool bTrialMode) {
            this.DefaultUserCheckResult = DefaultUserCheckResult;
            this.username_enc = username_enc;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string passcode_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string clientGuid;
        
        public CheckUserNameRequest() {
        }
        
        public CheckUserNameRequest(string key_enc, string username_enc, string passcode_enc, byte[] hash, string clientGuid) {
            this.key_enc = key_enc;
            this.username_enc = username_enc;
            this.passcode_enc = passcode_enc;
            this.hash = hash;
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckUserNameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool bTrialMode;
        
        public CheckUserNameResponse() {
        }
        
        public CheckUserNameResponse(bool CheckUserNameResult, string err_msg, bool bTrialMode) {
            this.CheckUserNameResult = CheckUserNameResult;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromMdb", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromMdbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string filename_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string command_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] hash;
        
        public GetDataSetFromMdbRequest() {
        }
        
        public GetDataSetFromMdbRequest(string key_enc, string filename_enc, string command_enc, byte[] hash) {
            this.key_enc = key_enc;
            this.filename_enc = filename_enc;
            this.command_enc = command_enc;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromMdbResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromMdbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataSetFromMdbResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        public GetDataSetFromMdbResponse() {
        }
        
        public GetDataSetFromMdbResponse(string GetDataSetFromMdbResult, string err_msg) {
            this.GetDataSetFromMdbResult = GetDataSetFromMdbResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromDsn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromDsnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dsn_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string command_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] hash;
        
        public GetDataSetFromDsnRequest() {
        }
        
        public GetDataSetFromDsnRequest(string key_enc, string dsn_enc, string command_enc, byte[] hash) {
            this.key_enc = key_enc;
            this.dsn_enc = dsn_enc;
            this.command_enc = command_enc;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromDsnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromDsnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataSetFromDsnResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        public GetDataSetFromDsnResponse() {
        }
        
        public GetDataSetFromDsnResponse(string GetDataSetFromDsnResult, string err_msg) {
            this.GetDataSetFromDsnResult = GetDataSetFromDsnResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetCommand", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dsn_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string command_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string guid;
        
        public DataSetCommandRequest() {
        }
        
        public DataSetCommandRequest(string key_enc, string dsn_enc, string command_enc, byte[] hash, string guid) {
            this.key_enc = key_enc;
            this.dsn_enc = dsn_enc;
            this.command_enc = command_enc;
            this.hash = hash;
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetCommandResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DataSetCommandResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        public DataSetCommandResponse() {
        }
        
        public DataSetCommandResponse(bool DataSetCommandResult, string err_msg) {
            this.DataSetCommandResult = DataSetCommandResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConnectionStringDbType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConnectionStringDbTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dsn_enc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] hash;
        
        public GetConnectionStringDbTypeRequest() {
        }
        
        public GetConnectionStringDbTypeRequest(string key_enc, string dsn_enc, byte[] hash) {
            this.key_enc = key_enc;
            this.dsn_enc = dsn_enc;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConnectionStringDbTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConnectionStringDbTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetConnectionStringDbTypeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dbtype;
        
        public GetConnectionStringDbTypeResponse() {
        }
        
        public GetConnectionStringDbTypeResponse(bool GetConnectionStringDbTypeResult, int dbtype) {
            this.GetConnectionStringDbTypeResult = GetConnectionStringDbTypeResult;
            this.dbtype = dbtype;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebService3Channel : AutoLib.ServiceReferenceService3.IWebService3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3Client : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceService3.IWebService3>, AutoLib.ServiceReferenceService3.IWebService3 {
        
        public WebService3Client() {
        }
        
        public WebService3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.GetConversationKeyResponse AutoLib.ServiceReferenceService3.IWebService3.GetConversationKey(AutoLib.ServiceReferenceService3.GetConversationKeyRequest request) {
            return base.Channel.GetConversationKey(request);
        }
        
        public string GetConversationKey(string request, out string key2_enc, out string key3_enc, out string key4_enc, out string key5_enc) {
            AutoLib.ServiceReferenceService3.GetConversationKeyRequest inValue = new AutoLib.ServiceReferenceService3.GetConversationKeyRequest();
            inValue.request = request;
            AutoLib.ServiceReferenceService3.GetConversationKeyResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).GetConversationKey(inValue);
            key2_enc = retVal.key2_enc;
            key3_enc = retVal.key3_enc;
            key4_enc = retVal.key4_enc;
            key5_enc = retVal.key5_enc;
            return retVal.GetConversationKeyResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetConversationKeyResponse> GetConversationKeyAsync(AutoLib.ServiceReferenceService3.GetConversationKeyRequest request) {
            return base.Channel.GetConversationKeyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.DefaultUserCheckResponse AutoLib.ServiceReferenceService3.IWebService3.DefaultUserCheck(AutoLib.ServiceReferenceService3.DefaultUserCheckRequest request) {
            return base.Channel.DefaultUserCheck(request);
        }
        
        public bool DefaultUserCheck(string key_enc, byte[] hash, string clientGuid, out string username_enc, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceService3.DefaultUserCheckRequest inValue = new AutoLib.ServiceReferenceService3.DefaultUserCheckRequest();
            inValue.key_enc = key_enc;
            inValue.hash = hash;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceService3.DefaultUserCheckResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).DefaultUserCheck(inValue);
            username_enc = retVal.username_enc;
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.DefaultUserCheckResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.DefaultUserCheckResponse> DefaultUserCheckAsync(AutoLib.ServiceReferenceService3.DefaultUserCheckRequest request) {
            return base.Channel.DefaultUserCheckAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.CheckUserNameResponse AutoLib.ServiceReferenceService3.IWebService3.CheckUserName(AutoLib.ServiceReferenceService3.CheckUserNameRequest request) {
            return base.Channel.CheckUserName(request);
        }
        
        public bool CheckUserName(string key_enc, string username_enc, string passcode_enc, byte[] hash, string clientGuid, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceService3.CheckUserNameRequest inValue = new AutoLib.ServiceReferenceService3.CheckUserNameRequest();
            inValue.key_enc = key_enc;
            inValue.username_enc = username_enc;
            inValue.passcode_enc = passcode_enc;
            inValue.hash = hash;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceService3.CheckUserNameResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).CheckUserName(inValue);
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.CheckUserNameResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.CheckUserNameResponse> CheckUserNameAsync(AutoLib.ServiceReferenceService3.CheckUserNameRequest request) {
            return base.Channel.CheckUserNameAsync(request);
        }
        
        public bool WriteCurr(string key_enc, string username_enc, string computername_enc, string tag_enc, string val_enc, byte[] hash, string guid) {
            return base.Channel.WriteCurr(key_enc, username_enc, computername_enc, tag_enc, val_enc, hash, guid);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCurrAsync(string key_enc, string username_enc, string computername_enc, string tag_enc, string val_enc, byte[] hash, string guid) {
            return base.Channel.WriteCurrAsync(key_enc, username_enc, computername_enc, tag_enc, val_enc, hash, guid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.GetDataSetFromMdbResponse AutoLib.ServiceReferenceService3.IWebService3.GetDataSetFromMdb(AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest request) {
            return base.Channel.GetDataSetFromMdb(request);
        }
        
        public string GetDataSetFromMdb(string key_enc, string filename_enc, string command_enc, byte[] hash, out string err_msg) {
            AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest inValue = new AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest();
            inValue.key_enc = key_enc;
            inValue.filename_enc = filename_enc;
            inValue.command_enc = command_enc;
            inValue.hash = hash;
            AutoLib.ServiceReferenceService3.GetDataSetFromMdbResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).GetDataSetFromMdb(inValue);
            err_msg = retVal.err_msg;
            return retVal.GetDataSetFromMdbResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetDataSetFromMdbResponse> GetDataSetFromMdbAsync(AutoLib.ServiceReferenceService3.GetDataSetFromMdbRequest request) {
            return base.Channel.GetDataSetFromMdbAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.GetDataSetFromDsnResponse AutoLib.ServiceReferenceService3.IWebService3.GetDataSetFromDsn(AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest request) {
            return base.Channel.GetDataSetFromDsn(request);
        }
        
        public string GetDataSetFromDsn(string key_enc, string dsn_enc, string command_enc, byte[] hash, out string err_msg) {
            AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest inValue = new AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest();
            inValue.key_enc = key_enc;
            inValue.dsn_enc = dsn_enc;
            inValue.command_enc = command_enc;
            inValue.hash = hash;
            AutoLib.ServiceReferenceService3.GetDataSetFromDsnResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).GetDataSetFromDsn(inValue);
            err_msg = retVal.err_msg;
            return retVal.GetDataSetFromDsnResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetDataSetFromDsnResponse> GetDataSetFromDsnAsync(AutoLib.ServiceReferenceService3.GetDataSetFromDsnRequest request) {
            return base.Channel.GetDataSetFromDsnAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.DataSetCommandResponse AutoLib.ServiceReferenceService3.IWebService3.DataSetCommand(AutoLib.ServiceReferenceService3.DataSetCommandRequest request) {
            return base.Channel.DataSetCommand(request);
        }
        
        public bool DataSetCommand(string key_enc, string dsn_enc, string command_enc, byte[] hash, string guid, out string err_msg) {
            AutoLib.ServiceReferenceService3.DataSetCommandRequest inValue = new AutoLib.ServiceReferenceService3.DataSetCommandRequest();
            inValue.key_enc = key_enc;
            inValue.dsn_enc = dsn_enc;
            inValue.command_enc = command_enc;
            inValue.hash = hash;
            inValue.guid = guid;
            AutoLib.ServiceReferenceService3.DataSetCommandResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).DataSetCommand(inValue);
            err_msg = retVal.err_msg;
            return retVal.DataSetCommandResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.DataSetCommandResponse> DataSetCommandAsync(AutoLib.ServiceReferenceService3.DataSetCommandRequest request) {
            return base.Channel.DataSetCommandAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeResponse AutoLib.ServiceReferenceService3.IWebService3.GetConnectionStringDbType(AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest request) {
            return base.Channel.GetConnectionStringDbType(request);
        }
        
        public bool GetConnectionStringDbType(string key_enc, string dsn_enc, byte[] hash, out int dbtype) {
            AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest inValue = new AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest();
            inValue.key_enc = key_enc;
            inValue.dsn_enc = dsn_enc;
            inValue.hash = hash;
            AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeResponse retVal = ((AutoLib.ServiceReferenceService3.IWebService3)(this)).GetConnectionStringDbType(inValue);
            dbtype = retVal.dbtype;
            return retVal.GetConnectionStringDbTypeResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeResponse> GetConnectionStringDbTypeAsync(AutoLib.ServiceReferenceService3.GetConnectionStringDbTypeRequest request) {
            return base.Channel.GetConnectionStringDbTypeAsync(request);
        }
    }
}
