//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceReport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceReport.IServiceReport")]
    public interface IServiceReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportLists", ReplyAction="http://tempuri.org/IServiceReport/GetReportListsResponse")]
        string[] GetReportLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportLists", ReplyAction="http://tempuri.org/IServiceReport/GetReportListsResponse")]
        System.Threading.Tasks.Task<string[]> GetReportListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStruct", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructResponse")]
        byte[] GetReportStruct(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStruct", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructResponse")]
        System.Threading.Tasks.Task<byte[]> GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructWithDic", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructWithDicResponse")]
        byte[] GetReportStructWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructWithDic", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructWithDicResponse")]
        System.Threading.Tasks.Task<byte[]> GetReportStructWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/ReportSetVar", ReplyAction="http://tempuri.org/IServiceReport/ReportSetVarResponse")]
        bool ReportSetVar(string name, string val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/ReportSetVar", ReplyAction="http://tempuri.org/IServiceReport/ReportSetVarResponse")]
        System.Threading.Tasks.Task<bool> ReportSetVarAsync(string name, string val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructJson", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructJsonResponse")]
        string GetReportStructJson(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructJson", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructJsonResponse")]
        System.Threading.Tasks.Task<string> GetReportStructJsonAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructWithDicJson", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructWithDicJsonResponse")]
        string GetReportStructWithDicJson(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportStructWithDicJson", ReplyAction="http://tempuri.org/IServiceReport/GetReportStructWithDicJsonResponse")]
        System.Threading.Tasks.Task<string> GetReportStructWithDicJsonAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportBitmapPngs", ReplyAction="http://tempuri.org/IServiceReport/GetReportBitmapPngsResponse")]
        byte[][] GetReportBitmapPngs(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportBitmapPngs", ReplyAction="http://tempuri.org/IServiceReport/GetReportBitmapPngsResponse")]
        System.Threading.Tasks.Task<byte[][]> GetReportBitmapPngsAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportBitmapPngsWithDic", ReplyAction="http://tempuri.org/IServiceReport/GetReportBitmapPngsWithDicResponse")]
        byte[][] GetReportBitmapPngsWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReport/GetReportBitmapPngsWithDic", ReplyAction="http://tempuri.org/IServiceReport/GetReportBitmapPngsWithDicResponse")]
        System.Threading.Tasks.Task<byte[][]> GetReportBitmapPngsWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceReportChannel : AutoLib.ServiceReferenceReport.IServiceReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceReportClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceReport.IServiceReport>, AutoLib.ServiceReferenceReport.IServiceReport {
        
        public ServiceReportClient() {
        }
        
        public ServiceReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetReportLists() {
            return base.Channel.GetReportLists();
        }
        
        public System.Threading.Tasks.Task<string[]> GetReportListsAsync() {
            return base.Channel.GetReportListsAsync();
        }
        
        public byte[] GetReportStruct(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStruct(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructAsync(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public byte[] GetReportStructWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDic(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetReportStructWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDicAsync(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public bool ReportSetVar(string name, string val) {
            return base.Channel.ReportSetVar(name, val);
        }
        
        public System.Threading.Tasks.Task<bool> ReportSetVarAsync(string name, string val) {
            return base.Channel.ReportSetVarAsync(name, val);
        }
        
        public string GetReportStructJson(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructJson(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<string> GetReportStructJsonAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructJsonAsync(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public string GetReportStructWithDicJson(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDicJson(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<string> GetReportStructWithDicJsonAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDicJsonAsync(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }

        public byte[][] GetReportBitmapPngs(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportBitmapPngs(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }

        public System.Threading.Tasks.Task<byte[][]> GetReportBitmapPngsAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportBitmapPngsAsync(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }

        public byte[][] GetReportBitmapPngsWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportBitmapPngsWithDic(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }

        public System.Threading.Tasks.Task<byte[][]> GetReportBitmapPngsWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportBitmapPngsWithDicAsync(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
    }
}
