//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceDataSet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataSet.IServiceDataSet")]
    public interface IServiceDataSet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetDataSetFromMdb", ReplyAction="http://tempuri.org/IServiceDataSet/GetDataSetFromMdbResponse")]
        AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbResponse GetDataSetFromMdb(AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetDataSetFromMdb", ReplyAction="http://tempuri.org/IServiceDataSet/GetDataSetFromMdbResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbResponse> GetDataSetFromMdbAsync(AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetDataSetFromDsn", ReplyAction="http://tempuri.org/IServiceDataSet/GetDataSetFromDsnResponse")]
        AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnResponse GetDataSetFromDsn(AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetDataSetFromDsn", ReplyAction="http://tempuri.org/IServiceDataSet/GetDataSetFromDsnResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnResponse> GetDataSetFromDsnAsync(AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/DataSetCommand", ReplyAction="http://tempuri.org/IServiceDataSet/DataSetCommandResponse")]
        AutoLib.ServiceReferenceDataSet.DataSetCommandResponse DataSetCommand(AutoLib.ServiceReferenceDataSet.DataSetCommandRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/DataSetCommand", ReplyAction="http://tempuri.org/IServiceDataSet/DataSetCommandResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.DataSetCommandResponse> DataSetCommandAsync(AutoLib.ServiceReferenceDataSet.DataSetCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetConnectionStringDbType", ReplyAction="http://tempuri.org/IServiceDataSet/GetConnectionStringDbTypeResponse")]
        AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeResponse GetConnectionStringDbType(AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataSet/GetConnectionStringDbType", ReplyAction="http://tempuri.org/IServiceDataSet/GetConnectionStringDbTypeResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeResponse> GetConnectionStringDbTypeAsync(AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromMdb", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromMdbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string command;
        
        public GetDataSetFromMdbRequest() {
        }
        
        public GetDataSetFromMdbRequest(string filename, string command) {
            this.filename = filename;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromMdbResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromMdbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetDataSetFromMdbResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public GetDataSetFromMdbResponse() {
        }
        
        public GetDataSetFromMdbResponse(System.Data.DataSet GetDataSetFromMdbResult, string error) {
            this.GetDataSetFromMdbResult = GetDataSetFromMdbResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromDsn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromDsnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string command;
        
        public GetDataSetFromDsnRequest() {
        }
        
        public GetDataSetFromDsnRequest(string dsn, string command) {
            this.dsn = dsn;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSetFromDsnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataSetFromDsnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetDataSetFromDsnResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public GetDataSetFromDsnResponse() {
        }
        
        public GetDataSetFromDsnResponse(System.Data.DataSet GetDataSetFromDsnResult, string error) {
            this.GetDataSetFromDsnResult = GetDataSetFromDsnResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetCommand", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string command;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string guid;
        
        public DataSetCommandRequest() {
        }
        
        public DataSetCommandRequest(string dsn, string command, string guid) {
            this.dsn = dsn;
            this.command = command;
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataSetCommandResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataSetCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DataSetCommandResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public DataSetCommandResponse() {
        }
        
        public DataSetCommandResponse(bool DataSetCommandResult, string error) {
            this.DataSetCommandResult = DataSetCommandResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConnectionStringDbType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConnectionStringDbTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dsn;
        
        public GetConnectionStringDbTypeRequest() {
        }
        
        public GetConnectionStringDbTypeRequest(string dsn) {
            this.dsn = dsn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConnectionStringDbTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConnectionStringDbTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetConnectionStringDbTypeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dbtype;
        
        public GetConnectionStringDbTypeResponse() {
        }
        
        public GetConnectionStringDbTypeResponse(bool GetConnectionStringDbTypeResult, int dbtype) {
            this.GetConnectionStringDbTypeResult = GetConnectionStringDbTypeResult;
            this.dbtype = dbtype;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataSetChannel : AutoLib.ServiceReferenceDataSet.IServiceDataSet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataSetClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceDataSet.IServiceDataSet>, AutoLib.ServiceReferenceDataSet.IServiceDataSet {
        
        public ServiceDataSetClient() {
        }
        
        public ServiceDataSetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataSetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataSetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataSetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbResponse AutoLib.ServiceReferenceDataSet.IServiceDataSet.GetDataSetFromMdb(AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest request) {
            return base.Channel.GetDataSetFromMdb(request);
        }
        
        public System.Data.DataSet GetDataSetFromMdb(string filename, string command, out string error) {
            AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest inValue = new AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest();
            inValue.filename = filename;
            inValue.command = command;
            AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbResponse retVal = ((AutoLib.ServiceReferenceDataSet.IServiceDataSet)(this)).GetDataSetFromMdb(inValue);
            error = retVal.error;
            return retVal.GetDataSetFromMdbResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbResponse> GetDataSetFromMdbAsync(AutoLib.ServiceReferenceDataSet.GetDataSetFromMdbRequest request) {
            return base.Channel.GetDataSetFromMdbAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnResponse AutoLib.ServiceReferenceDataSet.IServiceDataSet.GetDataSetFromDsn(AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest request) {
            return base.Channel.GetDataSetFromDsn(request);
        }
        
        public System.Data.DataSet GetDataSetFromDsn(string dsn, string command, out string error) {
            AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest inValue = new AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest();
            inValue.dsn = dsn;
            inValue.command = command;
            AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnResponse retVal = ((AutoLib.ServiceReferenceDataSet.IServiceDataSet)(this)).GetDataSetFromDsn(inValue);
            error = retVal.error;
            return retVal.GetDataSetFromDsnResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnResponse> GetDataSetFromDsnAsync(AutoLib.ServiceReferenceDataSet.GetDataSetFromDsnRequest request) {
            return base.Channel.GetDataSetFromDsnAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceDataSet.DataSetCommandResponse AutoLib.ServiceReferenceDataSet.IServiceDataSet.DataSetCommand(AutoLib.ServiceReferenceDataSet.DataSetCommandRequest request) {
            return base.Channel.DataSetCommand(request);
        }
        
        public bool DataSetCommand(string dsn, string command, string guid, out string error) {
            AutoLib.ServiceReferenceDataSet.DataSetCommandRequest inValue = new AutoLib.ServiceReferenceDataSet.DataSetCommandRequest();
            inValue.dsn = dsn;
            inValue.command = command;
            inValue.guid = guid;
            AutoLib.ServiceReferenceDataSet.DataSetCommandResponse retVal = ((AutoLib.ServiceReferenceDataSet.IServiceDataSet)(this)).DataSetCommand(inValue);
            error = retVal.error;
            return retVal.DataSetCommandResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.DataSetCommandResponse> DataSetCommandAsync(AutoLib.ServiceReferenceDataSet.DataSetCommandRequest request) {
            return base.Channel.DataSetCommandAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeResponse AutoLib.ServiceReferenceDataSet.IServiceDataSet.GetConnectionStringDbType(AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest request) {
            return base.Channel.GetConnectionStringDbType(request);
        }
        
        public bool GetConnectionStringDbType(string dsn, out int dbtype) {
            AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest inValue = new AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest();
            inValue.dsn = dsn;
            AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeResponse retVal = ((AutoLib.ServiceReferenceDataSet.IServiceDataSet)(this)).GetConnectionStringDbType(inValue);
            dbtype = retVal.dbtype;
            return retVal.GetConnectionStringDbTypeResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeResponse> GetConnectionStringDbTypeAsync(AutoLib.ServiceReferenceDataSet.GetConnectionStringDbTypeRequest request) {
            return base.Channel.GetConnectionStringDbTypeAsync(request);
        }
    }
}
