//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceDownLoadProject {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfServiceDownLoadProject.DownloadResponse", Namespace="http://schemas.datacontract.org/2004/07/PortalServerWeb.AutoWeb.Service")]
    [System.SerializableAttribute()]
    public partial class WcfServiceDownLoadProjectDownloadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FileTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoLib.ServiceReferenceDownLoadProject.ResultType ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileTime {
            get {
                return this.FileTimeField;
            }
            set {
                if ((this.FileTimeField.Equals(value) != true)) {
                    this.FileTimeField = value;
                    this.RaisePropertyChanged("FileTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutoLib.ServiceReferenceDownLoadProject.ResultType Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://tempuri.org/")]
    public enum ResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        failed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        matched = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        download = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        notfound = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDownLoadProject.IServiceDownLoadProject")]
    public interface IServiceDownLoadProject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDownLoadProject/Download", ReplyAction="http://tempuri.org/IServiceDownLoadProject/DownloadResponse")]
        AutoLib.ServiceReferenceDownLoadProject.WcfServiceDownLoadProjectDownloadResponse Download(string dir, string filename, bool compare_flag, System.DateTime file_time, long file_size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDownLoadProject/Download", ReplyAction="http://tempuri.org/IServiceDownLoadProject/DownloadResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceDownLoadProject.WcfServiceDownLoadProjectDownloadResponse> DownloadAsync(string dir, string filename, bool compare_flag, System.DateTime file_time, long file_size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDownLoadProjectChannel : AutoLib.ServiceReferenceDownLoadProject.IServiceDownLoadProject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDownLoadProjectClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceDownLoadProject.IServiceDownLoadProject>, AutoLib.ServiceReferenceDownLoadProject.IServiceDownLoadProject {
        
        public ServiceDownLoadProjectClient() {
        }
        
        public ServiceDownLoadProjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDownLoadProjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDownLoadProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDownLoadProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AutoLib.ServiceReferenceDownLoadProject.WcfServiceDownLoadProjectDownloadResponse Download(string dir, string filename, bool compare_flag, System.DateTime file_time, long file_size) {
            return base.Channel.Download(dir, filename, compare_flag, file_time, file_size);
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceDownLoadProject.WcfServiceDownLoadProjectDownloadResponse> DownloadAsync(string dir, string filename, bool compare_flag, System.DateTime file_time, long file_size) {
            return base.Channel.DownloadAsync(dir, filename, compare_flag, file_time, file_size);
        }
    }
}
