//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTools.ServiceReferenceSmsServiceSend3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSmsServiceSend3.ServiceSend3Soap")]
    public interface ServiceSend3Soap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 username_hash이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingTest", ReplyAction="*")]
        WebTools.ServiceReferenceSmsServiceSend3.PingTestResponse PingTest(WebTools.ServiceReferenceSmsServiceSend3.PingTestRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 tel_recv이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByAdmin", ReplyAction="*")]
        WebTools.ServiceReferenceSmsServiceSend3.SendByAdminResponse SendByAdmin(WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 username이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByAutoBase", ReplyAction="*")]
        WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseResponse SendByAutoBase(WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingTest", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.PingTestRequestBody Body;
        
        public PingTestRequest() {
        }
        
        public PingTestRequest(WebTools.ServiceReferenceSmsServiceSend3.PingTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username_hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] passcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string seed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] hash;
        
        public PingTestRequestBody() {
        }
        
        public PingTestRequestBody(string username_hash, byte[] passcode, string seed, byte[] hash) {
            this.username_hash = username_hash;
            this.passcode = passcode;
            this.seed = seed;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.PingTestResponseBody Body;
        
        public PingTestResponse() {
        }
        
        public PingTestResponse(WebTools.ServiceReferenceSmsServiceSend3.PingTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PingTestResult;
        
        public PingTestResponseBody() {
        }
        
        public PingTestResponseBody(int PingTestResult) {
            this.PingTestResult = PingTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendByAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendByAdmin", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequestBody Body;
        
        public SendByAdminRequest() {
        }
        
        public SendByAdminRequest(WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendByAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tel_recv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tel_send;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sms_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string seed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] hash;
        
        public SendByAdminRequestBody() {
        }
        
        public SendByAdminRequestBody(string tel_recv, string tel_send, string msg, int sms_type, string seed, byte[] hash) {
            this.tel_recv = tel_recv;
            this.tel_send = tel_send;
            this.msg = msg;
            this.sms_type = sms_type;
            this.seed = seed;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendByAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendByAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.SendByAdminResponseBody Body;
        
        public SendByAdminResponse() {
        }
        
        public SendByAdminResponse(WebTools.ServiceReferenceSmsServiceSend3.SendByAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendByAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendByAdminResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public SendByAdminResponseBody() {
        }
        
        public SendByAdminResponseBody(bool SendByAdminResult, string err_msg) {
            this.SendByAdminResult = SendByAdminResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendByAutoBaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendByAutoBase", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequestBody Body;
        
        public SendByAutoBaseRequest() {
        }
        
        public SendByAutoBaseRequest(WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendByAutoBaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] passcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tel_recv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tel_send;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string seed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int sms_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ui_culture;
        
        public SendByAutoBaseRequestBody() {
        }
        
        public SendByAutoBaseRequestBody(string username, byte[] passcode, string tel_recv, string tel_send, string msg, string seed, byte[] hash, int sms_type, string ui_culture) {
            this.username = username;
            this.passcode = passcode;
            this.tel_recv = tel_recv;
            this.tel_send = tel_send;
            this.msg = msg;
            this.seed = seed;
            this.hash = hash;
            this.sms_type = sms_type;
            this.ui_culture = ui_culture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendByAutoBaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendByAutoBaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseResponseBody Body;
        
        public SendByAutoBaseResponse() {
        }
        
        public SendByAutoBaseResponse(WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendByAutoBaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendByAutoBaseResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public SendByAutoBaseResponseBody() {
        }
        
        public SendByAutoBaseResponseBody(bool SendByAutoBaseResult, string err_msg) {
            this.SendByAutoBaseResult = SendByAutoBaseResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSend3SoapChannel : WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSend3SoapClient : System.ServiceModel.ClientBase<WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap>, WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap {
        
        public ServiceSend3SoapClient() {
        }
        
        public ServiceSend3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSend3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSend3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSend3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTools.ServiceReferenceSmsServiceSend3.PingTestResponse WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap.PingTest(WebTools.ServiceReferenceSmsServiceSend3.PingTestRequest request) {
            return base.Channel.PingTest(request);
        }
        
        public int PingTest(string username_hash, byte[] passcode, string seed, byte[] hash) {
            WebTools.ServiceReferenceSmsServiceSend3.PingTestRequest inValue = new WebTools.ServiceReferenceSmsServiceSend3.PingTestRequest();
            inValue.Body = new WebTools.ServiceReferenceSmsServiceSend3.PingTestRequestBody();
            inValue.Body.username_hash = username_hash;
            inValue.Body.passcode = passcode;
            inValue.Body.seed = seed;
            inValue.Body.hash = hash;
            WebTools.ServiceReferenceSmsServiceSend3.PingTestResponse retVal = ((WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap)(this)).PingTest(inValue);
            return retVal.Body.PingTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTools.ServiceReferenceSmsServiceSend3.SendByAdminResponse WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap.SendByAdmin(WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequest request) {
            return base.Channel.SendByAdmin(request);
        }
        
        public bool SendByAdmin(string tel_recv, string tel_send, string msg, int sms_type, string seed, byte[] hash, out string err_msg) {
            WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequest inValue = new WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequest();
            inValue.Body = new WebTools.ServiceReferenceSmsServiceSend3.SendByAdminRequestBody();
            inValue.Body.tel_recv = tel_recv;
            inValue.Body.tel_send = tel_send;
            inValue.Body.msg = msg;
            inValue.Body.sms_type = sms_type;
            inValue.Body.seed = seed;
            inValue.Body.hash = hash;
            WebTools.ServiceReferenceSmsServiceSend3.SendByAdminResponse retVal = ((WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap)(this)).SendByAdmin(inValue);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.SendByAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseResponse WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap.SendByAutoBase(WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequest request) {
            return base.Channel.SendByAutoBase(request);
        }
        
        public bool SendByAutoBase(string username, byte[] passcode, string tel_recv, string tel_send, string msg, string seed, byte[] hash, int sms_type, string ui_culture, out string err_msg) {
            WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequest inValue = new WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequest();
            inValue.Body = new WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseRequestBody();
            inValue.Body.username = username;
            inValue.Body.passcode = passcode;
            inValue.Body.tel_recv = tel_recv;
            inValue.Body.tel_send = tel_send;
            inValue.Body.msg = msg;
            inValue.Body.seed = seed;
            inValue.Body.hash = hash;
            inValue.Body.sms_type = sms_type;
            inValue.Body.ui_culture = ui_culture;
            WebTools.ServiceReferenceSmsServiceSend3.SendByAutoBaseResponse retVal = ((WebTools.ServiceReferenceSmsServiceSend3.ServiceSend3Soap)(this)).SendByAutoBase(inValue);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.SendByAutoBaseResult;
        }
    }
}
