//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferencePreset {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePreset.IWcfServicePreset")]
    public interface IWcfServicePreset {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/GetPresetList", ReplyAction="http://tempuri.org/IServicePreset/GetPresetListResponse")]
        AutoLib.ServiceReferencePreset.GetPresetListResponse GetPresetList(AutoLib.ServiceReferencePreset.GetPresetListRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/GetPresetList", ReplyAction="http://tempuri.org/IServicePreset/GetPresetListResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.GetPresetListResponse> GetPresetListAsync(AutoLib.ServiceReferencePreset.GetPresetListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/GetPreset", ReplyAction="http://tempuri.org/IServicePreset/GetPresetResponse")]
        AutoLib.ServiceReferencePreset.GetPresetResponse GetPreset(AutoLib.ServiceReferencePreset.GetPresetRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/GetPreset", ReplyAction="http://tempuri.org/IServicePreset/GetPresetResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.GetPresetResponse> GetPresetAsync(AutoLib.ServiceReferencePreset.GetPresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/SavePreset", ReplyAction="http://tempuri.org/IServicePreset/SavePresetResponse")]
        AutoLib.ServiceReferencePreset.SavePresetResponse SavePreset(AutoLib.ServiceReferencePreset.SavePresetRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/SavePreset", ReplyAction="http://tempuri.org/IServicePreset/SavePresetResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.SavePresetResponse> SavePresetAsync(AutoLib.ServiceReferencePreset.SavePresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/DeletePreset", ReplyAction="http://tempuri.org/IServicePreset/DeletePresetResponse")]
        AutoLib.ServiceReferencePreset.DeletePresetResponse DeletePreset(AutoLib.ServiceReferencePreset.DeletePresetRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/DeletePreset", ReplyAction="http://tempuri.org/IServicePreset/DeletePresetResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.DeletePresetResponse> DeletePresetAsync(AutoLib.ServiceReferencePreset.DeletePresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/ApplyPreset", ReplyAction="http://tempuri.org/IServicePreset/ApplyPresetResponse")]
        AutoLib.ServiceReferencePreset.ApplyPresetResponse ApplyPreset(AutoLib.ServiceReferencePreset.ApplyPresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/ApplyPreset", ReplyAction="http://tempuri.org/IServicePreset/ApplyPresetResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.ApplyPresetResponse> ApplyPresetAsync(AutoLib.ServiceReferencePreset.ApplyPresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/CapturePreset", ReplyAction="http://tempuri.org/IServicePreset/CapturePresetResponse")]
        AutoLib.ServiceReferencePreset.CapturePresetResponse CapturePreset(AutoLib.ServiceReferencePreset.CapturePresetRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePreset/CapturePreset", ReplyAction="http://tempuri.org/IServicePreset/CapturePresetResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.CapturePresetResponse> CapturePresetAsync(AutoLib.ServiceReferencePreset.CapturePresetRequest request);
    }

    // ===== GetPresetList =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPresetListRequest {

        public GetPresetListRequest() {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPresetListResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetPresetListResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public GetPresetListResponse() {
        }

        public GetPresetListResponse(string GetPresetListResult, string error) {
            this.GetPresetListResult = GetPresetListResult;
            this.error = error;
        }
    }

    // ===== GetPreset =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPreset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPresetRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string presetName;

        public GetPresetRequest() {
        }

        public GetPresetRequest(string presetName) {
            this.presetName = presetName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPresetResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetPresetResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public GetPresetResponse() {
        }

        public GetPresetResponse(string GetPresetResult, string error) {
            this.GetPresetResult = GetPresetResult;
            this.error = error;
        }
    }

    // ===== SavePreset =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePreset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePresetRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string presetName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string json;

        public SavePresetRequest() {
        }

        public SavePresetRequest(string presetName, string json) {
            this.presetName = presetName;
            this.json = json;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePresetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePresetResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SavePresetResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public SavePresetResponse() {
        }

        public SavePresetResponse(bool SavePresetResult, string error) {
            this.SavePresetResult = SavePresetResult;
            this.error = error;
        }
    }

    // ===== DeletePreset =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePreset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePresetRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string presetName;

        public DeletePresetRequest() {
        }

        public DeletePresetRequest(string presetName) {
            this.presetName = presetName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePresetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePresetResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeletePresetResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public DeletePresetResponse() {
        }

        public DeletePresetResponse(bool DeletePresetResult, string error) {
            this.DeletePresetResult = DeletePresetResult;
            this.error = error;
        }
    }

    // ===== ApplyPreset =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyPreset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyPresetRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string presetName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string variantName;

        public ApplyPresetRequest() {
        }

        public ApplyPresetRequest(string presetName, string variantName) {
            this.presetName = presetName;
            this.variantName = variantName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyPresetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyPresetResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ApplyPresetResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public ApplyPresetResponse() {
        }

        public ApplyPresetResponse(bool ApplyPresetResult, string error) {
            this.ApplyPresetResult = ApplyPresetResult;
            this.error = error;
        }
    }

    // ===== CapturePreset =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapturePreset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CapturePresetRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string templatePreset;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string variantName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string saveName;

        public CapturePresetRequest() {
        }

        public CapturePresetRequest(string templatePreset, string variantName, string saveName) {
            this.templatePreset = templatePreset;
            this.variantName = variantName;
            this.saveName = saveName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapturePresetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CapturePresetResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CapturePresetResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public CapturePresetResponse() {
        }

        public CapturePresetResponse(bool CapturePresetResult, string error) {
            this.CapturePresetResult = CapturePresetResult;
            this.error = error;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServicePresetChannel : AutoLib.ServiceReferencePreset.IWcfServicePreset, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServicePresetClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferencePreset.IWcfServicePreset>, AutoLib.ServiceReferencePreset.IWcfServicePreset {

        public WcfServicePresetClient() {
        }

        public WcfServicePresetClient(string endpointConfigurationName) :
                base(endpointConfigurationName) {
        }

        public WcfServicePresetClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public WcfServicePresetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public WcfServicePresetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        // ===== GetPresetList =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.GetPresetListResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.GetPresetList(AutoLib.ServiceReferencePreset.GetPresetListRequest request) {
            return base.Channel.GetPresetList(request);
        }

        public string GetPresetList(out string error) {
            AutoLib.ServiceReferencePreset.GetPresetListRequest inValue = new AutoLib.ServiceReferencePreset.GetPresetListRequest();
            AutoLib.ServiceReferencePreset.GetPresetListResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).GetPresetList(inValue);
            error = retVal.error;
            return retVal.GetPresetListResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.GetPresetListResponse> GetPresetListAsync(AutoLib.ServiceReferencePreset.GetPresetListRequest request) {
            return base.Channel.GetPresetListAsync(request);
        }

        // ===== GetPreset =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.GetPresetResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.GetPreset(AutoLib.ServiceReferencePreset.GetPresetRequest request) {
            return base.Channel.GetPreset(request);
        }

        public string GetPreset(string presetName, out string error) {
            AutoLib.ServiceReferencePreset.GetPresetRequest inValue = new AutoLib.ServiceReferencePreset.GetPresetRequest();
            inValue.presetName = presetName;
            AutoLib.ServiceReferencePreset.GetPresetResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).GetPreset(inValue);
            error = retVal.error;
            return retVal.GetPresetResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.GetPresetResponse> GetPresetAsync(AutoLib.ServiceReferencePreset.GetPresetRequest request) {
            return base.Channel.GetPresetAsync(request);
        }

        // ===== SavePreset =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.SavePresetResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.SavePreset(AutoLib.ServiceReferencePreset.SavePresetRequest request) {
            return base.Channel.SavePreset(request);
        }

        public bool SavePreset(string presetName, string json, out string error) {
            AutoLib.ServiceReferencePreset.SavePresetRequest inValue = new AutoLib.ServiceReferencePreset.SavePresetRequest();
            inValue.presetName = presetName;
            inValue.json = json;
            AutoLib.ServiceReferencePreset.SavePresetResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).SavePreset(inValue);
            error = retVal.error;
            return retVal.SavePresetResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.SavePresetResponse> SavePresetAsync(AutoLib.ServiceReferencePreset.SavePresetRequest request) {
            return base.Channel.SavePresetAsync(request);
        }

        // ===== DeletePreset =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.DeletePresetResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.DeletePreset(AutoLib.ServiceReferencePreset.DeletePresetRequest request) {
            return base.Channel.DeletePreset(request);
        }

        public bool DeletePreset(string presetName, out string error) {
            AutoLib.ServiceReferencePreset.DeletePresetRequest inValue = new AutoLib.ServiceReferencePreset.DeletePresetRequest();
            inValue.presetName = presetName;
            AutoLib.ServiceReferencePreset.DeletePresetResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).DeletePreset(inValue);
            error = retVal.error;
            return retVal.DeletePresetResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.DeletePresetResponse> DeletePresetAsync(AutoLib.ServiceReferencePreset.DeletePresetRequest request) {
            return base.Channel.DeletePresetAsync(request);
        }

        // ===== ApplyPreset =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.ApplyPresetResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.ApplyPreset(AutoLib.ServiceReferencePreset.ApplyPresetRequest request) {
            return base.Channel.ApplyPreset(request);
        }

        public bool ApplyPreset(string presetName, string variantName, out string error) {
            AutoLib.ServiceReferencePreset.ApplyPresetRequest inValue = new AutoLib.ServiceReferencePreset.ApplyPresetRequest();
            inValue.presetName = presetName;
            inValue.variantName = variantName;
            AutoLib.ServiceReferencePreset.ApplyPresetResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).ApplyPreset(inValue);
            error = retVal.error;
            return retVal.ApplyPresetResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.ApplyPresetResponse> ApplyPresetAsync(AutoLib.ServiceReferencePreset.ApplyPresetRequest request) {
            return base.Channel.ApplyPresetAsync(request);
        }

        // ===== CapturePreset =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferencePreset.CapturePresetResponse AutoLib.ServiceReferencePreset.IWcfServicePreset.CapturePreset(AutoLib.ServiceReferencePreset.CapturePresetRequest request) {
            return base.Channel.CapturePreset(request);
        }

        public bool CapturePreset(string templatePreset, string variantName, string saveName, out string error) {
            AutoLib.ServiceReferencePreset.CapturePresetRequest inValue = new AutoLib.ServiceReferencePreset.CapturePresetRequest();
            inValue.templatePreset = templatePreset;
            inValue.variantName = variantName;
            inValue.saveName = saveName;
            AutoLib.ServiceReferencePreset.CapturePresetResponse retVal = ((AutoLib.ServiceReferencePreset.IWcfServicePreset)(this)).CapturePreset(inValue);
            error = retVal.error;
            return retVal.CapturePresetResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferencePreset.CapturePresetResponse> CapturePresetAsync(AutoLib.ServiceReferencePreset.CapturePresetRequest request) {
            return base.Channel.CapturePresetAsync(request);
        }
    }
}
