//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceExcelReport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceExcelReport.IServiceExcelReport")]
    public interface IServiceExcelReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExcelReport/GetReportStruct", ReplyAction="http://tempuri.org/IServiceExcelReport/GetReportStructResponse")]
        string GetReportStruct(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExcelReport/GetReportStruct", ReplyAction="http://tempuri.org/IServiceExcelReport/GetReportStructResponse")]
        System.Threading.Tasks.Task<string> GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExcelReport/GetReportStructWithDic", ReplyAction="http://tempuri.org/IServiceExcelReport/GetReportStructWithDicResponse")]
        string GetReportStructWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExcelReport/GetReportStructWithDic", ReplyAction="http://tempuri.org/IServiceExcelReport/GetReportStructWithDicResponse")]
        System.Threading.Tasks.Task<string> GetReportStructWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExcelReportChannel : AutoLib.ServiceReferenceExcelReport.IServiceExcelReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExcelReportClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceExcelReport.IServiceExcelReport>, AutoLib.ServiceReferenceExcelReport.IServiceExcelReport {
        
        public ServiceExcelReportClient() {
        }
        
        public ServiceExcelReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExcelReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExcelReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExcelReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetReportStruct(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStruct(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<string> GetReportStructAsync(string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructAsync(filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public string GetReportStructWithDic(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDic(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
        
        public System.Threading.Tasks.Task<string> GetReportStructWithDicAsync(string[] keys, string[] values, string filename, System.DateTime tHand, System.DateTime tAuto, System.DateTime tMinListFr, System.DateTime tMinListTo, int hand_auto) {
            return base.Channel.GetReportStructWithDicAsync(keys, values, filename, tHand, tAuto, tMinListFr, tMinListTo, hand_auto);
        }
    }
}
