//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpLib.ServiceReferenceHelp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceHelp.WebServiceHelpSoap")]
    public interface WebServiceHelpSoap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 HelloWorldResult이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HelpLib.ServiceReferenceHelp.HelloWorldResponse HelloWorld(HelpLib.ServiceReferenceHelp.HelloWorldRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 language이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckHelpLists", ReplyAction="*")]
        HelpLib.ServiceReferenceHelp.CheckHelpListsResponse CheckHelpLists(HelpLib.ServiceReferenceHelp.CheckHelpListsRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 language이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadFile", ReplyAction="*")]
        HelpLib.ServiceReferenceHelp.DownLoadFileResponse DownLoadFile(HelpLib.ServiceReferenceHelp.DownLoadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelpLib.ServiceReferenceHelp.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelpLib.ServiceReferenceHelp.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckHelpListsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckHelpLists", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.CheckHelpListsRequestBody Body;
        
        public CheckHelpListsRequest() {
        }
        
        public CheckHelpListsRequest(HelpLib.ServiceReferenceHelp.CheckHelpListsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckHelpListsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string language;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HelpLib.ServiceReferenceHelp.ArrayOfString files;
        
        public CheckHelpListsRequestBody() {
        }
        
        public CheckHelpListsRequestBody(string language, HelpLib.ServiceReferenceHelp.ArrayOfString files) {
            this.language = language;
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckHelpListsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckHelpListsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.CheckHelpListsResponseBody Body;
        
        public CheckHelpListsResponse() {
        }
        
        public CheckHelpListsResponse(HelpLib.ServiceReferenceHelp.CheckHelpListsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckHelpListsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HelpLib.ServiceReferenceHelp.ArrayOfString CheckHelpListsResult;
        
        public CheckHelpListsResponseBody() {
        }
        
        public CheckHelpListsResponseBody(HelpLib.ServiceReferenceHelp.ArrayOfString CheckHelpListsResult) {
            this.CheckHelpListsResult = CheckHelpListsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFile", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.DownLoadFileRequestBody Body;
        
        public DownLoadFileRequest() {
        }
        
        public DownLoadFileRequest(HelpLib.ServiceReferenceHelp.DownLoadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string language;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long pos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int size;
        
        public DownLoadFileRequestBody() {
        }
        
        public DownLoadFileRequestBody(string language, string file, long pos, int size) {
            this.language = language;
            this.file = file;
            this.pos = pos;
            this.size = size;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpLib.ServiceReferenceHelp.DownLoadFileResponseBody Body;
        
        public DownLoadFileResponse() {
        }
        
        public DownLoadFileResponse(HelpLib.ServiceReferenceHelp.DownLoadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownLoadFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public DownLoadFileResponseBody() {
        }
        
        public DownLoadFileResponseBody(byte[] DownLoadFileResult, string msg) {
            this.DownLoadFileResult = DownLoadFileResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceHelpSoapChannel : HelpLib.ServiceReferenceHelp.WebServiceHelpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceHelpSoapClient : System.ServiceModel.ClientBase<HelpLib.ServiceReferenceHelp.WebServiceHelpSoap>, HelpLib.ServiceReferenceHelp.WebServiceHelpSoap {
        
        public WebServiceHelpSoapClient() {
        }
        
        public WebServiceHelpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceHelpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHelpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHelpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpLib.ServiceReferenceHelp.HelloWorldResponse HelpLib.ServiceReferenceHelp.WebServiceHelpSoap.HelloWorld(HelpLib.ServiceReferenceHelp.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HelpLib.ServiceReferenceHelp.HelloWorldRequest inValue = new HelpLib.ServiceReferenceHelp.HelloWorldRequest();
            inValue.Body = new HelpLib.ServiceReferenceHelp.HelloWorldRequestBody();
            HelpLib.ServiceReferenceHelp.HelloWorldResponse retVal = ((HelpLib.ServiceReferenceHelp.WebServiceHelpSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpLib.ServiceReferenceHelp.CheckHelpListsResponse HelpLib.ServiceReferenceHelp.WebServiceHelpSoap.CheckHelpLists(HelpLib.ServiceReferenceHelp.CheckHelpListsRequest request) {
            return base.Channel.CheckHelpLists(request);
        }
        
        public HelpLib.ServiceReferenceHelp.ArrayOfString CheckHelpLists(string language, HelpLib.ServiceReferenceHelp.ArrayOfString files) {
            HelpLib.ServiceReferenceHelp.CheckHelpListsRequest inValue = new HelpLib.ServiceReferenceHelp.CheckHelpListsRequest();
            inValue.Body = new HelpLib.ServiceReferenceHelp.CheckHelpListsRequestBody();
            inValue.Body.language = language;
            inValue.Body.files = files;
            HelpLib.ServiceReferenceHelp.CheckHelpListsResponse retVal = ((HelpLib.ServiceReferenceHelp.WebServiceHelpSoap)(this)).CheckHelpLists(inValue);
            return retVal.Body.CheckHelpListsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpLib.ServiceReferenceHelp.DownLoadFileResponse HelpLib.ServiceReferenceHelp.WebServiceHelpSoap.DownLoadFile(HelpLib.ServiceReferenceHelp.DownLoadFileRequest request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public byte[] DownLoadFile(string language, string file, long pos, int size, out string msg) {
            HelpLib.ServiceReferenceHelp.DownLoadFileRequest inValue = new HelpLib.ServiceReferenceHelp.DownLoadFileRequest();
            inValue.Body = new HelpLib.ServiceReferenceHelp.DownLoadFileRequestBody();
            inValue.Body.language = language;
            inValue.Body.file = file;
            inValue.Body.pos = pos;
            inValue.Body.size = size;
            HelpLib.ServiceReferenceHelp.DownLoadFileResponse retVal = ((HelpLib.ServiceReferenceHelp.WebServiceHelpSoap)(this)).DownLoadFile(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.DownLoadFileResult;
        }
    }
}
