//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalMain.ServiceReferenceKeyLock {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://tempuri.org/", ItemName="base64Binary")]
    [System.SerializableAttribute()]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKeyLock.WebServiceKeyLockSoap")]
    public interface WebServiceKeyLockSoap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 HelloWorldResult이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LocalMain.ServiceReferenceKeyLock.HelloWorldResponse HelloWorld(LocalMain.ServiceReferenceKeyLock.HelloWorldRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 args이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadKeyFile", ReplyAction="*")]
        LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileResponse DownLoadKeyFile(LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LocalMain.ServiceReferenceKeyLock.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LocalMain.ServiceReferenceKeyLock.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalMain.ServiceReferenceKeyLock.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LocalMain.ServiceReferenceKeyLock.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadKeyFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadKeyFile", Namespace="http://tempuri.org/", Order=0)]
        public LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequestBody Body;
        
        public DownLoadKeyFileRequest() {
        }
        
        public DownLoadKeyFileRequest(LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadKeyFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LocalMain.ServiceReferenceKeyLock.ArrayOfBase64Binary args;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] hash;
        
        public DownLoadKeyFileRequestBody() {
        }
        
        public DownLoadKeyFileRequestBody(LocalMain.ServiceReferenceKeyLock.ArrayOfBase64Binary args, byte[] hash) {
            this.args = args;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadKeyFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadKeyFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileResponseBody Body;
        
        public DownLoadKeyFileResponse() {
        }
        
        public DownLoadKeyFileResponse(LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadKeyFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownLoadKeyFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public DownLoadKeyFileResponseBody() {
        }
        
        public DownLoadKeyFileResponseBody(byte[] DownLoadKeyFileResult, string err_msg) {
            this.DownLoadKeyFileResult = DownLoadKeyFileResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceKeyLockSoapChannel : LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceKeyLockSoapClient : System.ServiceModel.ClientBase<LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap>, LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap {
        
        public WebServiceKeyLockSoapClient() {
        }
        
        public WebServiceKeyLockSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceKeyLockSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKeyLockSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKeyLockSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalMain.ServiceReferenceKeyLock.HelloWorldResponse LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap.HelloWorld(LocalMain.ServiceReferenceKeyLock.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LocalMain.ServiceReferenceKeyLock.HelloWorldRequest inValue = new LocalMain.ServiceReferenceKeyLock.HelloWorldRequest();
            inValue.Body = new LocalMain.ServiceReferenceKeyLock.HelloWorldRequestBody();
            LocalMain.ServiceReferenceKeyLock.HelloWorldResponse retVal = ((LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileResponse LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap.DownLoadKeyFile(LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequest request) {
            return base.Channel.DownLoadKeyFile(request);
        }
        
        public byte[] DownLoadKeyFile(LocalMain.ServiceReferenceKeyLock.ArrayOfBase64Binary args, byte[] hash, out string err_msg) {
            LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequest inValue = new LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequest();
            inValue.Body = new LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileRequestBody();
            inValue.Body.args = args;
            inValue.Body.hash = hash;
            LocalMain.ServiceReferenceKeyLock.DownLoadKeyFileResponse retVal = ((LocalMain.ServiceReferenceKeyLock.WebServiceKeyLockSoap)(this)).DownLoadKeyFile(inValue);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.DownLoadKeyFileResult;
        }
    }
}
