//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace SMS.biz.autobase.sms.www {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSend2Soap", Namespace="http://tempuri.org/")]
    public partial class ServiceSend2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendByAutoBaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceSend2(string site) {
            //this.Url = "http://www.sms.autobase.biz/Protocol/ServiceSend2.asmx";
            this.Url = String.Format("http://{0}/Protocol/ServiceSend2.asmx", site);
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendCompletedEventHandler SendCompleted;
        
        /// <remarks/>
        public event PingTestCompletedEventHandler PingTestCompleted;
        
        /// <remarks/>
        public event SendByAutoBaseCompletedEventHandler SendByAutoBaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Send(string username, string phone_target, string phone_callback, string msg, int sms_type) {
            this.Invoke("Send", new object[] {
                        username,
                        phone_target,
                        phone_callback,
                        msg,
                        sms_type});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSend(string username, string phone_target, string phone_callback, string msg, int sms_type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Send", new object[] {
                        username,
                        phone_target,
                        phone_callback,
                        msg,
                        sms_type}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSend(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void SendAsync(string username, string phone_target, string phone_callback, string msg, int sms_type) {
            this.SendAsync(username, phone_target, phone_callback, msg, sms_type, null);
        }
        
        /// <remarks/>
        public void SendAsync(string username, string phone_target, string phone_callback, string msg, int sms_type, object userState) {
            if ((this.SendOperationCompleted == null)) {
                this.SendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOperationCompleted);
            }
            this.InvokeAsync("Send", new object[] {
                        username,
                        phone_target,
                        phone_callback,
                        msg,
                        sms_type}, this.SendOperationCompleted, userState);
        }
        
        private void OnSendOperationCompleted(object arg) {
            if ((this.SendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PingTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PingTest(string username, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] passcode) {
            object[] results = this.Invoke("PingTest", new object[] {
                        username,
                        passcode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPingTest(string username, byte[] passcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PingTest", new object[] {
                        username,
                        passcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndPingTest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PingTestAsync(string username, byte[] passcode) {
            this.PingTestAsync(username, passcode, null);
        }
        
        /// <remarks/>
        public void PingTestAsync(string username, byte[] passcode, object userState) {
            if ((this.PingTestOperationCompleted == null)) {
                this.PingTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingTestOperationCompleted);
            }
            this.InvokeAsync("PingTest", new object[] {
                        username,
                        passcode}, this.PingTestOperationCompleted, userState);
        }
        
        private void OnPingTestOperationCompleted(object arg) {
            if ((this.PingTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingTestCompleted(this, new PingTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendByAutoBase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendByAutoBase(string username, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] passcode, string tel_recv, string tel_send, string msg, int sms_type) {
            object[] results = this.Invoke("SendByAutoBase", new object[] {
                        username,
                        passcode,
                        tel_recv,
                        tel_send,
                        msg,
                        sms_type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendByAutoBase(string username, byte[] passcode, string tel_recv, string tel_send, string msg, int sms_type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendByAutoBase", new object[] {
                        username,
                        passcode,
                        tel_recv,
                        tel_send,
                        msg,
                        sms_type}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSendByAutoBase(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendByAutoBaseAsync(string username, byte[] passcode, string tel_recv, string tel_send, string msg, int sms_type) {
            this.SendByAutoBaseAsync(username, passcode, tel_recv, tel_send, msg, sms_type, null);
        }
        
        /// <remarks/>
        public void SendByAutoBaseAsync(string username, byte[] passcode, string tel_recv, string tel_send, string msg, int sms_type, object userState) {
            if ((this.SendByAutoBaseOperationCompleted == null)) {
                this.SendByAutoBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendByAutoBaseOperationCompleted);
            }
            this.InvokeAsync("SendByAutoBase", new object[] {
                        username,
                        passcode,
                        tel_recv,
                        tel_send,
                        msg,
                        sms_type}, this.SendByAutoBaseOperationCompleted, userState);
        }
        
        private void OnSendByAutoBaseOperationCompleted(object arg) {
            if ((this.SendByAutoBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendByAutoBaseCompleted(this, new SendByAutoBaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PingTestCompletedEventHandler(object sender, PingTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendByAutoBaseCompletedEventHandler(object sender, SendByAutoBaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendByAutoBaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendByAutoBaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591