//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceRecipe {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRecipe.IWcfServiceRecipe")]
    public interface IWcfServiceRecipe {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/GetRecipeList", ReplyAction="http://tempuri.org/IServiceRecipe/GetRecipeListResponse")]
        AutoLib.ServiceReferenceRecipe.GetRecipeListResponse GetRecipeList(AutoLib.ServiceReferenceRecipe.GetRecipeListRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/GetRecipeList", ReplyAction="http://tempuri.org/IServiceRecipe/GetRecipeListResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.GetRecipeListResponse> GetRecipeListAsync(AutoLib.ServiceReferenceRecipe.GetRecipeListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/GetRecipe", ReplyAction="http://tempuri.org/IServiceRecipe/GetRecipeResponse")]
        AutoLib.ServiceReferenceRecipe.GetRecipeResponse GetRecipe(AutoLib.ServiceReferenceRecipe.GetRecipeRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/GetRecipe", ReplyAction="http://tempuri.org/IServiceRecipe/GetRecipeResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.GetRecipeResponse> GetRecipeAsync(AutoLib.ServiceReferenceRecipe.GetRecipeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeDownload", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeDownloadResponse")]
        AutoLib.ServiceReferenceRecipe.RecipeDownloadResponse RecipeDownload(AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeDownload", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeDownloadResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeDownloadResponse> RecipeDownloadAsync(AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeUpload", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeUploadResponse")]
        AutoLib.ServiceReferenceRecipe.RecipeUploadResponse RecipeUpload(AutoLib.ServiceReferenceRecipe.RecipeUploadRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeUpload", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeUploadResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeUploadResponse> RecipeUploadAsync(AutoLib.ServiceReferenceRecipe.RecipeUploadRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeDownloadUnit", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeDownloadUnitResponse")]
        AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitResponse RecipeDownloadUnit(AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeDownloadUnit", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeDownloadUnitResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitResponse> RecipeDownloadUnitAsync(AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeUploadUnit", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeUploadUnitResponse")]
        AutoLib.ServiceReferenceRecipe.RecipeUploadUnitResponse RecipeUploadUnit(AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest request);

        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecipe/RecipeUploadUnit", ReplyAction="http://tempuri.org/IServiceRecipe/RecipeUploadUnitResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeUploadUnitResponse> RecipeUploadUnitAsync(AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest request);
    }

    // ===== GetRecipeList =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipeList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecipeListRequest {

        public GetRecipeListRequest() {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipeListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecipeListResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetRecipeListResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public GetRecipeListResponse() {
        }

        public GetRecipeListResponse(System.Data.DataSet GetRecipeListResult, string error) {
            this.GetRecipeListResult = GetRecipeListResult;
            this.error = error;
        }
    }

    // ===== GetRecipe =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecipeRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int recipeId;

        public GetRecipeRequest() {
        }

        public GetRecipeRequest(int recipeId) {
            this.recipeId = recipeId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecipeResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetRecipeResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public GetRecipeResponse() {
        }

        public GetRecipeResponse(System.Data.DataSet GetRecipeResult, string error) {
            this.GetRecipeResult = GetRecipeResult;
            this.error = error;
        }
    }

    // ===== RecipeDownload =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeDownloadRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recipeName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string clientGuid;

        public RecipeDownloadRequest() {
        }

        public RecipeDownloadRequest(string recipeName, string clientGuid) {
            this.recipeName = recipeName;
            this.clientGuid = clientGuid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeDownloadResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecipeDownloadResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public RecipeDownloadResponse() {
        }

        public RecipeDownloadResponse(bool RecipeDownloadResult, string error) {
            this.RecipeDownloadResult = RecipeDownloadResult;
            this.error = error;
        }
    }

    // ===== RecipeUpload =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeUpload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeUploadRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recipeName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string clientGuid;

        public RecipeUploadRequest() {
        }

        public RecipeUploadRequest(string recipeName, string clientGuid) {
            this.recipeName = recipeName;
            this.clientGuid = clientGuid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeUploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeUploadResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecipeUploadResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public RecipeUploadResponse() {
        }

        public RecipeUploadResponse(bool RecipeUploadResult, string error) {
            this.RecipeUploadResult = RecipeUploadResult;
            this.error = error;
        }
    }

    // ===== RecipeDownloadUnit =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeDownloadUnit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeDownloadUnitRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recipeName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string unitName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clientGuid;

        public RecipeDownloadUnitRequest() {
        }

        public RecipeDownloadUnitRequest(string recipeName, string unitName, string clientGuid) {
            this.recipeName = recipeName;
            this.unitName = unitName;
            this.clientGuid = clientGuid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeDownloadUnitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeDownloadUnitResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecipeDownloadUnitResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public RecipeDownloadUnitResponse() {
        }

        public RecipeDownloadUnitResponse(bool RecipeDownloadUnitResult, string error) {
            this.RecipeDownloadUnitResult = RecipeDownloadUnitResult;
            this.error = error;
        }
    }

    // ===== RecipeUploadUnit =====
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeUploadUnit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeUploadUnitRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recipeName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string unitName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clientGuid;

        public RecipeUploadUnitRequest() {
        }

        public RecipeUploadUnitRequest(string recipeName, string unitName, string clientGuid) {
            this.recipeName = recipeName;
            this.unitName = unitName;
            this.clientGuid = clientGuid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecipeUploadUnitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecipeUploadUnitResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecipeUploadUnitResult;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;

        public RecipeUploadUnitResponse() {
        }

        public RecipeUploadUnitResponse(bool RecipeUploadUnitResult, string error) {
            this.RecipeUploadUnitResult = RecipeUploadUnitResult;
            this.error = error;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceRecipeChannel : AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceRecipeClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe>, AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe {

        public WcfServiceRecipeClient() {
        }

        public WcfServiceRecipeClient(string endpointConfigurationName) :
                base(endpointConfigurationName) {
        }

        public WcfServiceRecipeClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public WcfServiceRecipeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public WcfServiceRecipeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        // ===== GetRecipeList =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.GetRecipeListResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.GetRecipeList(AutoLib.ServiceReferenceRecipe.GetRecipeListRequest request) {
            return base.Channel.GetRecipeList(request);
        }

        public System.Data.DataSet GetRecipeList(out string error) {
            AutoLib.ServiceReferenceRecipe.GetRecipeListRequest inValue = new AutoLib.ServiceReferenceRecipe.GetRecipeListRequest();
            AutoLib.ServiceReferenceRecipe.GetRecipeListResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).GetRecipeList(inValue);
            error = retVal.error;
            return retVal.GetRecipeListResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.GetRecipeListResponse> GetRecipeListAsync(AutoLib.ServiceReferenceRecipe.GetRecipeListRequest request) {
            return base.Channel.GetRecipeListAsync(request);
        }

        // ===== GetRecipe =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.GetRecipeResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.GetRecipe(AutoLib.ServiceReferenceRecipe.GetRecipeRequest request) {
            return base.Channel.GetRecipe(request);
        }

        public System.Data.DataSet GetRecipe(int recipeId, out string error) {
            AutoLib.ServiceReferenceRecipe.GetRecipeRequest inValue = new AutoLib.ServiceReferenceRecipe.GetRecipeRequest();
            inValue.recipeId = recipeId;
            AutoLib.ServiceReferenceRecipe.GetRecipeResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).GetRecipe(inValue);
            error = retVal.error;
            return retVal.GetRecipeResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.GetRecipeResponse> GetRecipeAsync(AutoLib.ServiceReferenceRecipe.GetRecipeRequest request) {
            return base.Channel.GetRecipeAsync(request);
        }

        // ===== RecipeDownload =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.RecipeDownloadResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.RecipeDownload(AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest request) {
            return base.Channel.RecipeDownload(request);
        }

        public bool RecipeDownload(string recipeName, string clientGuid, out string error) {
            AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest inValue = new AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest();
            inValue.recipeName = recipeName;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceRecipe.RecipeDownloadResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).RecipeDownload(inValue);
            error = retVal.error;
            return retVal.RecipeDownloadResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeDownloadResponse> RecipeDownloadAsync(AutoLib.ServiceReferenceRecipe.RecipeDownloadRequest request) {
            return base.Channel.RecipeDownloadAsync(request);
        }

        // ===== RecipeUpload =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.RecipeUploadResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.RecipeUpload(AutoLib.ServiceReferenceRecipe.RecipeUploadRequest request) {
            return base.Channel.RecipeUpload(request);
        }

        public bool RecipeUpload(string recipeName, string clientGuid, out string error) {
            AutoLib.ServiceReferenceRecipe.RecipeUploadRequest inValue = new AutoLib.ServiceReferenceRecipe.RecipeUploadRequest();
            inValue.recipeName = recipeName;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceRecipe.RecipeUploadResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).RecipeUpload(inValue);
            error = retVal.error;
            return retVal.RecipeUploadResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeUploadResponse> RecipeUploadAsync(AutoLib.ServiceReferenceRecipe.RecipeUploadRequest request) {
            return base.Channel.RecipeUploadAsync(request);
        }

        // ===== RecipeDownloadUnit =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.RecipeDownloadUnit(AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest request) {
            return base.Channel.RecipeDownloadUnit(request);
        }

        public bool RecipeDownloadUnit(string recipeName, string unitName, string clientGuid, out string error) {
            AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest inValue = new AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest();
            inValue.recipeName = recipeName;
            inValue.unitName = unitName;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).RecipeDownloadUnit(inValue);
            error = retVal.error;
            return retVal.RecipeDownloadUnitResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitResponse> RecipeDownloadUnitAsync(AutoLib.ServiceReferenceRecipe.RecipeDownloadUnitRequest request) {
            return base.Channel.RecipeDownloadUnitAsync(request);
        }

        // ===== RecipeUploadUnit =====
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceRecipe.RecipeUploadUnitResponse AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe.RecipeUploadUnit(AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest request) {
            return base.Channel.RecipeUploadUnit(request);
        }

        public bool RecipeUploadUnit(string recipeName, string unitName, string clientGuid, out string error) {
            AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest inValue = new AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest();
            inValue.recipeName = recipeName;
            inValue.unitName = unitName;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceRecipe.RecipeUploadUnitResponse retVal = ((AutoLib.ServiceReferenceRecipe.IWcfServiceRecipe)(this)).RecipeUploadUnit(inValue);
            error = retVal.error;
            return retVal.RecipeUploadUnitResult;
        }

        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceRecipe.RecipeUploadUnitResponse> RecipeUploadUnitAsync(AutoLib.ServiceReferenceRecipe.RecipeUploadUnitRequest request) {
            return base.Channel.RecipeUploadUnitAsync(request);
        }
    }
}
