//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace SilverlightAutoLibLocal.ServiceReferenceUserProtect {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUserProtect.ServiceUserProtectSoap")]
    public interface ServiceUserProtectSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CheckUserName", ReplyAction="*")]
        System.IAsyncResult BeginCheckUserName(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse EndCheckUserName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CheckUserNameWithVersion", ReplyAction="*")]
        System.IAsyncResult BeginCheckUserNameWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse EndCheckUserNameWithVersion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetUserCount", ReplyAction="*")]
        System.IAsyncResult BeginGetUserCount(System.AsyncCallback callback, object asyncState);
        
        int EndGetUserCount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DefaultUserCheck", ReplyAction="*")]
        System.IAsyncResult BeginDefaultUserCheck(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse EndDefaultUserCheck(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DefaultUserCheckWithVersion", ReplyAction="*")]
        System.IAsyncResult BeginDefaultUserCheckWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse EndDefaultUserCheckWithVersion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LogOut", ReplyAction="*")]
        System.IAsyncResult BeginLogOut(System.AsyncCallback callback, object asyncState);
        
        void EndLogOut(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserName", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequestBody Body;
        
        public CheckUserNameRequest() {
        }
        
        public CheckUserNameRequest(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckUserNameRequestBody() {
        }
        
        public CheckUserNameRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponseBody Body;
        
        public CheckUserNameResponse() {
        }
        
        public CheckUserNameResponse(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserNameResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public CheckUserNameResponseBody() {
        }
        
        public CheckUserNameResponseBody(bool CheckUserNameResult, string err_msg) {
            this.CheckUserNameResult = CheckUserNameResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserNameWithVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserNameWithVersion", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequestBody Body;
        
        public CheckUserNameWithVersionRequest() {
        }
        
        public CheckUserNameWithVersionRequest(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserNameWithVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckUserNameWithVersionRequestBody() {
        }
        
        public CheckUserNameWithVersionRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserNameWithVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserNameWithVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponseBody Body;
        
        public CheckUserNameWithVersionResponse() {
        }
        
        public CheckUserNameWithVersionResponse(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserNameWithVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserNameWithVersionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string err_msg;
        
        public CheckUserNameWithVersionResponseBody() {
        }
        
        public CheckUserNameWithVersionResponseBody(bool CheckUserNameWithVersionResult, string err_msg) {
            this.CheckUserNameWithVersionResult = CheckUserNameWithVersionResult;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultUserCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultUserCheck", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequestBody Body;
        
        public DefaultUserCheckRequest() {
        }
        
        public DefaultUserCheckRequest(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DefaultUserCheckRequestBody {
        
        public DefaultUserCheckRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultUserCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultUserCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponseBody Body;
        
        public DefaultUserCheckResponse() {
        }
        
        public DefaultUserCheckResponse(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DefaultUserCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DefaultUserCheckResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string err_msg;
        
        public DefaultUserCheckResponseBody() {
        }
        
        public DefaultUserCheckResponseBody(bool DefaultUserCheckResult, string username, string err_msg) {
            this.DefaultUserCheckResult = DefaultUserCheckResult;
            this.username = username;
            this.err_msg = err_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultUserCheckWithVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultUserCheckWithVersion", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequestBody Body;
        
        public DefaultUserCheckWithVersionRequest() {
        }
        
        public DefaultUserCheckWithVersionRequest(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DefaultUserCheckWithVersionRequestBody {
        
        public DefaultUserCheckWithVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultUserCheckWithVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultUserCheckWithVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponseBody Body;
        
        public DefaultUserCheckWithVersionResponse() {
        }
        
        public DefaultUserCheckWithVersionResponse(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DefaultUserCheckWithVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DefaultUserCheckWithVersionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string err_msg;
        
        public DefaultUserCheckWithVersionResponseBody() {
        }
        
        public DefaultUserCheckWithVersionResponseBody(bool DefaultUserCheckWithVersionResult, string username, string err_msg) {
            this.DefaultUserCheckWithVersionResult = DefaultUserCheckWithVersionResult;
            this.username = username;
            this.err_msg = err_msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceUserProtectSoapChannel : SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CheckUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string err_msg {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CheckUserNameWithVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserNameWithVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string err_msg {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetUserCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DefaultUserCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DefaultUserCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string username {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public string err_msg {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DefaultUserCheckWithVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DefaultUserCheckWithVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string username {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public string err_msg {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceUserProtectSoapClient : System.ServiceModel.ClientBase<SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap>, SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap {
        
        private BeginOperationDelegate onBeginCheckUserNameDelegate;
        
        private EndOperationDelegate onEndCheckUserNameDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckUserNameWithVersionDelegate;
        
        private EndOperationDelegate onEndCheckUserNameWithVersionDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserNameWithVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserCountDelegate;
        
        private EndOperationDelegate onEndGetUserCountDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserCountCompletedDelegate;
        
        private BeginOperationDelegate onBeginDefaultUserCheckDelegate;
        
        private EndOperationDelegate onEndDefaultUserCheckDelegate;
        
        private System.Threading.SendOrPostCallback onDefaultUserCheckCompletedDelegate;
        
        private BeginOperationDelegate onBeginDefaultUserCheckWithVersionDelegate;
        
        private EndOperationDelegate onEndDefaultUserCheckWithVersionDelegate;
        
        private System.Threading.SendOrPostCallback onDefaultUserCheckWithVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogOutDelegate;
        
        private EndOperationDelegate onEndLogOutDelegate;
        
        private System.Threading.SendOrPostCallback onLogOutCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceUserProtectSoapClient() {
        }
        
        public ServiceUserProtectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUserProtectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserProtectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserProtectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CheckUserNameCompletedEventArgs> CheckUserNameCompleted;
        
        public event System.EventHandler<CheckUserNameWithVersionCompletedEventArgs> CheckUserNameWithVersionCompleted;
        
        public event System.EventHandler<GetUserCountCompletedEventArgs> GetUserCountCompleted;
        
        public event System.EventHandler<DefaultUserCheckCompletedEventArgs> DefaultUserCheckCompleted;
        
        public event System.EventHandler<DefaultUserCheckWithVersionCompletedEventArgs> DefaultUserCheckWithVersionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LogOutCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginCheckUserName(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUserName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCheckUserName(string username, string password, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginCheckUserName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndCheckUserName(System.IAsyncResult result) {
            return base.Channel.EndCheckUserName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndCheckUserName(System.IAsyncResult result, out string err_msg) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndCheckUserName(result);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.CheckUserNameResult;
        }
        
        private System.IAsyncResult OnBeginCheckUserName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginCheckUserName(username, password, callback, asyncState);
        }
        
        private object[] OnEndCheckUserName(System.IAsyncResult result) {
            string err_msg = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndCheckUserName(result, out err_msg);
            return new object[] {
                    err_msg,
                    retVal};
        }
        
        private void OnCheckUserNameCompleted(object state) {
            if ((this.CheckUserNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserNameCompleted(this, new CheckUserNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserNameAsync(string username, string password) {
            this.CheckUserNameAsync(username, password, null);
        }
        
        public void CheckUserNameAsync(string username, string password, object userState) {
            if ((this.onBeginCheckUserNameDelegate == null)) {
                this.onBeginCheckUserNameDelegate = new BeginOperationDelegate(this.OnBeginCheckUserName);
            }
            if ((this.onEndCheckUserNameDelegate == null)) {
                this.onEndCheckUserNameDelegate = new EndOperationDelegate(this.OnEndCheckUserName);
            }
            if ((this.onCheckUserNameCompletedDelegate == null)) {
                this.onCheckUserNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserNameCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserNameDelegate, new object[] {
                        username,
                        password}, this.onEndCheckUserNameDelegate, this.onCheckUserNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginCheckUserNameWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUserNameWithVersion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCheckUserNameWithVersion(string username, string password, System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginCheckUserNameWithVersion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndCheckUserNameWithVersion(System.IAsyncResult result) {
            return base.Channel.EndCheckUserNameWithVersion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndCheckUserNameWithVersion(System.IAsyncResult result, out string err_msg) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndCheckUserNameWithVersion(result);
            err_msg = retVal.Body.err_msg;
            return retVal.Body.CheckUserNameWithVersionResult;
        }
        
        private System.IAsyncResult OnBeginCheckUserNameWithVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginCheckUserNameWithVersion(username, password, callback, asyncState);
        }
        
        private object[] OnEndCheckUserNameWithVersion(System.IAsyncResult result) {
            string err_msg = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndCheckUserNameWithVersion(result, out err_msg);
            return new object[] {
                    err_msg,
                    retVal};
        }
        
        private void OnCheckUserNameWithVersionCompleted(object state) {
            if ((this.CheckUserNameWithVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserNameWithVersionCompleted(this, new CheckUserNameWithVersionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserNameWithVersionAsync(string username, string password) {
            this.CheckUserNameWithVersionAsync(username, password, null);
        }
        
        public void CheckUserNameWithVersionAsync(string username, string password, object userState) {
            if ((this.onBeginCheckUserNameWithVersionDelegate == null)) {
                this.onBeginCheckUserNameWithVersionDelegate = new BeginOperationDelegate(this.OnBeginCheckUserNameWithVersion);
            }
            if ((this.onEndCheckUserNameWithVersionDelegate == null)) {
                this.onEndCheckUserNameWithVersionDelegate = new EndOperationDelegate(this.OnEndCheckUserNameWithVersion);
            }
            if ((this.onCheckUserNameWithVersionCompletedDelegate == null)) {
                this.onCheckUserNameWithVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserNameWithVersionCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserNameWithVersionDelegate, new object[] {
                        username,
                        password}, this.onEndCheckUserNameWithVersionDelegate, this.onCheckUserNameWithVersionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginGetUserCount(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserCount(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndGetUserCount(System.IAsyncResult result) {
            return base.Channel.EndGetUserCount(result);
        }
        
        private System.IAsyncResult OnBeginGetUserCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginGetUserCount(callback, asyncState);
        }
        
        private object[] OnEndGetUserCount(System.IAsyncResult result) {
            int retVal = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndGetUserCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserCountCompleted(object state) {
            if ((this.GetUserCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserCountCompleted(this, new GetUserCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserCountAsync() {
            this.GetUserCountAsync(null);
        }
        
        public void GetUserCountAsync(object userState) {
            if ((this.onBeginGetUserCountDelegate == null)) {
                this.onBeginGetUserCountDelegate = new BeginOperationDelegate(this.OnBeginGetUserCount);
            }
            if ((this.onEndGetUserCountDelegate == null)) {
                this.onEndGetUserCountDelegate = new EndOperationDelegate(this.OnEndGetUserCount);
            }
            if ((this.onGetUserCountCompletedDelegate == null)) {
                this.onGetUserCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserCountCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserCountDelegate, null, this.onEndGetUserCountDelegate, this.onGetUserCountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginDefaultUserCheck(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDefaultUserCheck(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDefaultUserCheck(System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequestBody();
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginDefaultUserCheck(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndDefaultUserCheck(System.IAsyncResult result) {
            return base.Channel.EndDefaultUserCheck(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndDefaultUserCheck(System.IAsyncResult result, out string username, out string err_msg) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndDefaultUserCheck(result);
            username = retVal.Body.username;
            err_msg = retVal.Body.err_msg;
            return retVal.Body.DefaultUserCheckResult;
        }
        
        private System.IAsyncResult OnBeginDefaultUserCheck(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDefaultUserCheck(callback, asyncState);
        }
        
        private object[] OnEndDefaultUserCheck(System.IAsyncResult result) {
            string username = this.GetDefaultValueForInitialization<string>();
            string err_msg = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndDefaultUserCheck(result, out username, out err_msg);
            return new object[] {
                    username,
                    err_msg,
                    retVal};
        }
        
        private void OnDefaultUserCheckCompleted(object state) {
            if ((this.DefaultUserCheckCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DefaultUserCheckCompleted(this, new DefaultUserCheckCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DefaultUserCheckAsync() {
            this.DefaultUserCheckAsync(null);
        }
        
        public void DefaultUserCheckAsync(object userState) {
            if ((this.onBeginDefaultUserCheckDelegate == null)) {
                this.onBeginDefaultUserCheckDelegate = new BeginOperationDelegate(this.OnBeginDefaultUserCheck);
            }
            if ((this.onEndDefaultUserCheckDelegate == null)) {
                this.onEndDefaultUserCheckDelegate = new EndOperationDelegate(this.OnEndDefaultUserCheck);
            }
            if ((this.onDefaultUserCheckCompletedDelegate == null)) {
                this.onDefaultUserCheckCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDefaultUserCheckCompleted);
            }
            base.InvokeAsync(this.onBeginDefaultUserCheckDelegate, null, this.onEndDefaultUserCheckDelegate, this.onDefaultUserCheckCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginDefaultUserCheckWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDefaultUserCheckWithVersion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDefaultUserCheckWithVersion(System.AsyncCallback callback, object asyncState) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest inValue = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest();
            inValue.Body = new SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequestBody();
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginDefaultUserCheckWithVersion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndDefaultUserCheckWithVersion(System.IAsyncResult result) {
            return base.Channel.EndDefaultUserCheckWithVersion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndDefaultUserCheckWithVersion(System.IAsyncResult result, out string username, out string err_msg) {
            SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse retVal = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndDefaultUserCheckWithVersion(result);
            username = retVal.Body.username;
            err_msg = retVal.Body.err_msg;
            return retVal.Body.DefaultUserCheckWithVersionResult;
        }
        
        private System.IAsyncResult OnBeginDefaultUserCheckWithVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDefaultUserCheckWithVersion(callback, asyncState);
        }
        
        private object[] OnEndDefaultUserCheckWithVersion(System.IAsyncResult result) {
            string username = this.GetDefaultValueForInitialization<string>();
            string err_msg = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndDefaultUserCheckWithVersion(result, out username, out err_msg);
            return new object[] {
                    username,
                    err_msg,
                    retVal};
        }
        
        private void OnDefaultUserCheckWithVersionCompleted(object state) {
            if ((this.DefaultUserCheckWithVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DefaultUserCheckWithVersionCompleted(this, new DefaultUserCheckWithVersionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DefaultUserCheckWithVersionAsync() {
            this.DefaultUserCheckWithVersionAsync(null);
        }
        
        public void DefaultUserCheckWithVersionAsync(object userState) {
            if ((this.onBeginDefaultUserCheckWithVersionDelegate == null)) {
                this.onBeginDefaultUserCheckWithVersionDelegate = new BeginOperationDelegate(this.OnBeginDefaultUserCheckWithVersion);
            }
            if ((this.onEndDefaultUserCheckWithVersionDelegate == null)) {
                this.onEndDefaultUserCheckWithVersionDelegate = new EndOperationDelegate(this.OnEndDefaultUserCheckWithVersion);
            }
            if ((this.onDefaultUserCheckWithVersionCompletedDelegate == null)) {
                this.onDefaultUserCheckWithVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDefaultUserCheckWithVersionCompleted);
            }
            base.InvokeAsync(this.onBeginDefaultUserCheckWithVersionDelegate, null, this.onEndDefaultUserCheckWithVersionDelegate, this.onDefaultUserCheckWithVersionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.BeginLogOut(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogOut(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap.EndLogOut(System.IAsyncResult result) {
            base.Channel.EndLogOut(result);
        }
        
        private System.IAsyncResult OnBeginLogOut(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).BeginLogOut(callback, asyncState);
        }
        
        private object[] OnEndLogOut(System.IAsyncResult result) {
            ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap)(this)).EndLogOut(result);
            return null;
        }
        
        private void OnLogOutCompleted(object state) {
            if ((this.LogOutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogOutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogOutAsync() {
            this.LogOutAsync(null);
        }
        
        public void LogOutAsync(object userState) {
            if ((this.onBeginLogOutDelegate == null)) {
                this.onBeginLogOutDelegate = new BeginOperationDelegate(this.OnBeginLogOut);
            }
            if ((this.onEndLogOutDelegate == null)) {
                this.onEndLogOutDelegate = new EndOperationDelegate(this.OnEndLogOut);
            }
            if ((this.onLogOutCompletedDelegate == null)) {
                this.onLogOutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogOutCompleted);
            }
            base.InvokeAsync(this.onBeginLogOutDelegate, null, this.onEndLogOutDelegate, this.onLogOutCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap CreateChannel() {
            return new ServiceUserProtectSoapClientChannel(this);
        }
        
        private class ServiceUserProtectSoapClientChannel : ChannelBase<SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap>, SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap {
            
            public ServiceUserProtectSoapClientChannel(System.ServiceModel.ClientBase<SilverlightAutoLibLocal.ServiceReferenceUserProtect.ServiceUserProtectSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCheckUserName(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CheckUserName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse EndCheckUserName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameResponse)(base.EndInvoke("CheckUserName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCheckUserNameWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CheckUserNameWithVersion", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse EndCheckUserNameWithVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse)(base.EndInvoke("CheckUserNameWithVersion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserCount(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetUserCount", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetUserCount(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetUserCount", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDefaultUserCheck(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DefaultUserCheck", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse EndDefaultUserCheck(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckResponse)(base.EndInvoke("DefaultUserCheck", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDefaultUserCheckWithVersion(SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DefaultUserCheckWithVersion", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse EndDefaultUserCheckWithVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse _result = ((SilverlightAutoLibLocal.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse)(base.EndInvoke("DefaultUserCheckWithVersion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogOut(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LogOut", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLogOut(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("LogOut", _args, result);
            }
        }
    }
}
