//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.ServiceReferenceUserProtect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCountInfo", Namespace="http://schemas.datacontract.org/2004/07/PortalServerWeb.AutoWeb.Service")]
    [System.SerializableAttribute()]
    public partial class UserCountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KeylockCountk__BackingFieldField;
        
        private int LicenseCountk__BackingFieldField;
        
        private int TrialCountk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<KeylockCount>k__BackingField", IsRequired=true)]
        public int KeylockCountk__BackingField {
            get {
                return this.KeylockCountk__BackingFieldField;
            }
            set {
                if ((this.KeylockCountk__BackingFieldField.Equals(value) != true)) {
                    this.KeylockCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("KeylockCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LicenseCount>k__BackingField", IsRequired=true)]
        public int LicenseCountk__BackingField {
            get {
                return this.LicenseCountk__BackingFieldField;
            }
            set {
                if ((this.LicenseCountk__BackingFieldField.Equals(value) != true)) {
                    this.LicenseCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("LicenseCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TrialCount>k__BackingField", IsRequired=true)]
        public int TrialCountk__BackingField {
            get {
                return this.TrialCountk__BackingFieldField;
            }
            set {
                if ((this.TrialCountk__BackingFieldField.Equals(value) != true)) {
                    this.TrialCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("TrialCountk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUserProtect.IServiceUserProtect")]
    public interface IServiceUserProtect {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/CheckUserName", ReplyAction="http://tempuri.org/IServiceUserProtect/CheckUserNameResponse")]
        AutoLib.ServiceReferenceUserProtect.CheckUserNameResponse CheckUserName(AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/CheckUserName", ReplyAction="http://tempuri.org/IServiceUserProtect/CheckUserNameResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.CheckUserNameResponse> CheckUserNameAsync(AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/CheckUserNameWithVersion", ReplyAction="http://tempuri.org/IServiceUserProtect/CheckUserNameWithVersionResponse")]
        AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse CheckUserNameWithVersion(AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/CheckUserNameWithVersion", ReplyAction="http://tempuri.org/IServiceUserProtect/CheckUserNameWithVersionResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse> CheckUserNameWithVersionAsync(AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/GetUserCount", ReplyAction="http://tempuri.org/IServiceUserProtect/GetUserCountResponse")]
        AutoLib.ServiceReferenceUserProtect.UserCountInfo GetUserCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/GetUserCount", ReplyAction="http://tempuri.org/IServiceUserProtect/GetUserCountResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.UserCountInfo> GetUserCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/DefaultUserCheck", ReplyAction="http://tempuri.org/IServiceUserProtect/DefaultUserCheckResponse")]
        AutoLib.ServiceReferenceUserProtect.DefaultUserCheckResponse DefaultUserCheck(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/DefaultUserCheck", ReplyAction="http://tempuri.org/IServiceUserProtect/DefaultUserCheckResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.DefaultUserCheckResponse> DefaultUserCheckAsync(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/DefaultUserCheckWithVersion", ReplyAction="http://tempuri.org/IServiceUserProtect/DefaultUserCheckWithVersionResponse")]
        AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse DefaultUserCheckWithVersion(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/DefaultUserCheckWithVersion", ReplyAction="http://tempuri.org/IServiceUserProtect/DefaultUserCheckWithVersionResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse> DefaultUserCheckWithVersionAsync(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/LogOut", ReplyAction="http://tempuri.org/IServiceUserProtect/LogOutResponse")]
        bool LogOut(string clientGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/LogOut", ReplyAction="http://tempuri.org/IServiceUserProtect/LogOutResponse")]
        System.Threading.Tasks.Task<bool> LogOutAsync(string clientGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/UpdateHeartbeat", ReplyAction="http://tempuri.org/IServiceUserProtect/UpdateHeartbeatResponse")]
        AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatResponse UpdateHeartbeat(AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/UpdateHeartbeat", ReplyAction="http://tempuri.org/IServiceUserProtect/UpdateHeartbeatResponse")]
        System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatResponse> UpdateHeartbeatAsync(AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/GetConnectionStatus", ReplyAction="http://tempuri.org/IServiceUserProtect/GetConnectionStatusResponse")]
        string GetConnectionStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUserProtect/GetConnectionStatus", ReplyAction="http://tempuri.org/IServiceUserProtect/GetConnectionStatusResponse")]
        System.Threading.Tasks.Task<string> GetConnectionStatusAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clientGuid;
        
        public CheckUserNameRequest() {
        }
        
        public CheckUserNameRequest(string username, string password, string clientGuid) {
            this.username = username;
            this.password = password;
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckUserNameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool bTrialMode;
        
        public CheckUserNameResponse() {
        }
        
        public CheckUserNameResponse(bool CheckUserNameResult, string err_msg, bool bTrialMode) {
            this.CheckUserNameResult = CheckUserNameResult;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserNameWithVersion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameWithVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clientGuid;
        
        public CheckUserNameWithVersionRequest() {
        }
        
        public CheckUserNameWithVersionRequest(string username, string password, string clientGuid) {
            this.username = username;
            this.password = password;
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserNameWithVersionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserNameWithVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckUserNameWithVersionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool bTrialMode;
        
        public CheckUserNameWithVersionResponse() {
        }
        
        public CheckUserNameWithVersionResponse(bool CheckUserNameWithVersionResult, string err_msg, bool bTrialMode) {
            this.CheckUserNameWithVersionResult = CheckUserNameWithVersionResult;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheck", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientGuid;
        
        public DefaultUserCheckRequest() {
        }
        
        public DefaultUserCheckRequest(string clientGuid) {
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheckResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DefaultUserCheckResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool bTrialMode;
        
        public DefaultUserCheckResponse() {
        }
        
        public DefaultUserCheckResponse(bool DefaultUserCheckResult, string username, string err_msg, bool bTrialMode) {
            this.DefaultUserCheckResult = DefaultUserCheckResult;
            this.username = username;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheckWithVersion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckWithVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientGuid;
        
        public DefaultUserCheckWithVersionRequest() {
        }
        
        public DefaultUserCheckWithVersionRequest(string clientGuid) {
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DefaultUserCheckWithVersionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DefaultUserCheckWithVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DefaultUserCheckWithVersionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string err_msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool bTrialMode;
        
        public DefaultUserCheckWithVersionResponse() {
        }
        
        public DefaultUserCheckWithVersionResponse(bool DefaultUserCheckWithVersionResult, string username, string err_msg, bool bTrialMode) {
            this.DefaultUserCheckWithVersionResult = DefaultUserCheckWithVersionResult;
            this.username = username;
            this.err_msg = err_msg;
            this.bTrialMode = bTrialMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateHeartbeat", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateHeartbeatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientGuid;
        
        public UpdateHeartbeatRequest() {
        }
        
        public UpdateHeartbeatRequest(string clientGuid) {
            this.clientGuid = clientGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateHeartbeatResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateHeartbeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateHeartbeatResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public UpdateHeartbeatResponse() {
        }
        
        public UpdateHeartbeatResponse(bool UpdateHeartbeatResult, string error) {
            this.UpdateHeartbeatResult = UpdateHeartbeatResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUserProtectChannel : AutoLib.ServiceReferenceUserProtect.IServiceUserProtect, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUserProtectClient : System.ServiceModel.ClientBase<AutoLib.ServiceReferenceUserProtect.IServiceUserProtect>, AutoLib.ServiceReferenceUserProtect.IServiceUserProtect {
        
        public ServiceUserProtectClient() {
        }
        
        public ServiceUserProtectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUserProtectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserProtectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserProtectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceUserProtect.CheckUserNameResponse AutoLib.ServiceReferenceUserProtect.IServiceUserProtect.CheckUserName(AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest request) {
            return base.Channel.CheckUserName(request);
        }
        
        public bool CheckUserName(string username, string password, string clientGuid, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest inValue = new AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceUserProtect.CheckUserNameResponse retVal = ((AutoLib.ServiceReferenceUserProtect.IServiceUserProtect)(this)).CheckUserName(inValue);
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.CheckUserNameResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.CheckUserNameResponse> CheckUserNameAsync(AutoLib.ServiceReferenceUserProtect.CheckUserNameRequest request) {
            return base.Channel.CheckUserNameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse AutoLib.ServiceReferenceUserProtect.IServiceUserProtect.CheckUserNameWithVersion(AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request) {
            return base.Channel.CheckUserNameWithVersion(request);
        }
        
        public bool CheckUserNameWithVersion(string username, string password, string clientGuid, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest inValue = new AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse retVal = ((AutoLib.ServiceReferenceUserProtect.IServiceUserProtect)(this)).CheckUserNameWithVersion(inValue);
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.CheckUserNameWithVersionResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionResponse> CheckUserNameWithVersionAsync(AutoLib.ServiceReferenceUserProtect.CheckUserNameWithVersionRequest request) {
            return base.Channel.CheckUserNameWithVersionAsync(request);
        }
        
        public AutoLib.ServiceReferenceUserProtect.UserCountInfo GetUserCount() {
            return base.Channel.GetUserCount();
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.UserCountInfo> GetUserCountAsync() {
            return base.Channel.GetUserCountAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceUserProtect.DefaultUserCheckResponse AutoLib.ServiceReferenceUserProtect.IServiceUserProtect.DefaultUserCheck(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest request) {
            return base.Channel.DefaultUserCheck(request);
        }
        
        public bool DefaultUserCheck(string clientGuid, out string username, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest inValue = new AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest();
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceUserProtect.DefaultUserCheckResponse retVal = ((AutoLib.ServiceReferenceUserProtect.IServiceUserProtect)(this)).DefaultUserCheck(inValue);
            username = retVal.username;
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.DefaultUserCheckResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.DefaultUserCheckResponse> DefaultUserCheckAsync(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckRequest request) {
            return base.Channel.DefaultUserCheckAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse AutoLib.ServiceReferenceUserProtect.IServiceUserProtect.DefaultUserCheckWithVersion(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request) {
            return base.Channel.DefaultUserCheckWithVersion(request);
        }
        
        public bool DefaultUserCheckWithVersion(string clientGuid, out string username, out string err_msg, out bool bTrialMode) {
            AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest inValue = new AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest();
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse retVal = ((AutoLib.ServiceReferenceUserProtect.IServiceUserProtect)(this)).DefaultUserCheckWithVersion(inValue);
            username = retVal.username;
            err_msg = retVal.err_msg;
            bTrialMode = retVal.bTrialMode;
            return retVal.DefaultUserCheckWithVersionResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionResponse> DefaultUserCheckWithVersionAsync(AutoLib.ServiceReferenceUserProtect.DefaultUserCheckWithVersionRequest request) {
            return base.Channel.DefaultUserCheckWithVersionAsync(request);
        }
        
        public bool LogOut(string clientGuid) {
            return base.Channel.LogOut(clientGuid);
        }
        
        public System.Threading.Tasks.Task<bool> LogOutAsync(string clientGuid) {
            return base.Channel.LogOutAsync(clientGuid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatResponse AutoLib.ServiceReferenceUserProtect.IServiceUserProtect.UpdateHeartbeat(AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest request) {
            return base.Channel.UpdateHeartbeat(request);
        }
        
        public bool UpdateHeartbeat(string clientGuid, out string error) {
            AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest inValue = new AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest();
            inValue.clientGuid = clientGuid;
            AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatResponse retVal = ((AutoLib.ServiceReferenceUserProtect.IServiceUserProtect)(this)).UpdateHeartbeat(inValue);
            error = retVal.error;
            return retVal.UpdateHeartbeatResult;
        }
        
        public System.Threading.Tasks.Task<AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatResponse> UpdateHeartbeatAsync(AutoLib.ServiceReferenceUserProtect.UpdateHeartbeatRequest request) {
            return base.Channel.UpdateHeartbeatAsync(request);
        }
        
        public string GetConnectionStatus() {
            return base.Channel.GetConnectionStatus();
        }
        
        public System.Threading.Tasks.Task<string> GetConnectionStatusAsync() {
            return base.Channel.GetConnectionStatusAsync();
        }
    }
}
