//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLib.WcfReferenceDataGateServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonMethodResult", Namespace="http://schemas.datacontract.org/2004/07/PortalServerWeb.AutoWeb.Service")]
    [System.SerializableAttribute()]
    public partial class CommonMethodResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[][] RecvField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] Recv {
            get {
                return this.RecvField;
            }
            set {
                if ((object.ReferenceEquals(this.RecvField, value) != true)) {
                    this.RecvField = value;
                    this.RaisePropertyChanged("Recv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfReferenceDataGateServer.IServiceDataGateServer")]
    public interface IServiceDataGateServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/CheckServerEvent", ReplyAction="http://tempuri.org/IServiceDataGateServer/CheckServerEventResponse")]
        string CheckServerEvent(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/CheckServerEvent", ReplyAction="http://tempuri.org/IServiceDataGateServer/CheckServerEventResponse")]
        System.Threading.Tasks.Task<string> CheckServerEventAsync(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/GetAlarmEvents", ReplyAction="http://tempuri.org/IServiceDataGateServer/GetAlarmEventsResponse")]
        string GetAlarmEvents(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/GetAlarmEvents", ReplyAction="http://tempuri.org/IServiceDataGateServer/GetAlarmEventsResponse")]
        System.Threading.Tasks.Task<string> GetAlarmEventsAsync(int id, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/ExecuteCommand", ReplyAction="http://tempuri.org/IServiceDataGateServer/ExecuteCommandResponse")]
        bool ExecuteCommand(int id, string command, string argument, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/ExecuteCommand", ReplyAction="http://tempuri.org/IServiceDataGateServer/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<bool> ExecuteCommandAsync(int id, string command, string argument, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/CommonMethod", ReplyAction="http://tempuri.org/IServiceDataGateServer/CommonMethodResponse")]
        AutoLib.WcfReferenceDataGateServer.CommonMethodResult CommonMethod(byte[][] send);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataGateServer/CommonMethod", ReplyAction="http://tempuri.org/IServiceDataGateServer/CommonMethodResponse")]
        System.Threading.Tasks.Task<AutoLib.WcfReferenceDataGateServer.CommonMethodResult> CommonMethodAsync(byte[][] send);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataGateServerChannel : AutoLib.WcfReferenceDataGateServer.IServiceDataGateServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataGateServerClient : System.ServiceModel.ClientBase<AutoLib.WcfReferenceDataGateServer.IServiceDataGateServer>, AutoLib.WcfReferenceDataGateServer.IServiceDataGateServer {
        
        public ServiceDataGateServerClient() {
        }
        
        public ServiceDataGateServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataGateServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataGateServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataGateServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckServerEvent(int id, string hash) {
            return base.Channel.CheckServerEvent(id, hash);
        }
        
        public System.Threading.Tasks.Task<string> CheckServerEventAsync(int id, string hash) {
            return base.Channel.CheckServerEventAsync(id, hash);
        }
        
        public string GetAlarmEvents(int id, string hash) {
            return base.Channel.GetAlarmEvents(id, hash);
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmEventsAsync(int id, string hash) {
            return base.Channel.GetAlarmEventsAsync(id, hash);
        }
        
        public bool ExecuteCommand(int id, string command, string argument, string hash) {
            return base.Channel.ExecuteCommand(id, command, argument, hash);
        }
        
        public System.Threading.Tasks.Task<bool> ExecuteCommandAsync(int id, string command, string argument, string hash) {
            return base.Channel.ExecuteCommandAsync(id, command, argument, hash);
        }
        
        public AutoLib.WcfReferenceDataGateServer.CommonMethodResult CommonMethod(byte[][] send) {
            return base.Channel.CommonMethod(send);
        }
        
        public System.Threading.Tasks.Task<AutoLib.WcfReferenceDataGateServer.CommonMethodResult> CommonMethodAsync(byte[][] send) {
            return base.Channel.CommonMethodAsync(send);
        }
    }
}
